// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/li_chao_tree

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

class LiChaoTree {
 public:
  struct Line {
    long long slope = 0;
    long long intercept = std::numeric_limits<long long>::max() / 4;
    long long value(long long x) const { return slope * x + intercept; }
  };

  LiChaoTree(long long min_x, long long max_x) : min_x_(min_x), max_x_(max_x) {}

  void add_line(long long slope, long long intercept) {
    const Line line{slope, intercept};
    add_line(root_, min_x_, max_x_, line);
    EDULCNI_VIS(edulcni::live::lines(
        "li_chao.inserted_line", std::vector<Line>{line}));
    EDULCNI_VIS(edulcni::live::array(
        "li_chao.domain", std::vector<long long>{min_x_, max_x_}));
    EDULCNI_STEP("Li Chao tree adds a line");
  }

  long long query(long long x) const {
    const long long result = query(root_.get(), min_x_, max_x_, x);
    EDULCNI_VIS(edulcni::live::value("li_chao.query_x", x));
    EDULCNI_VIS(edulcni::live::value("li_chao.result", result));
    EDULCNI_STEP("Li Chao tree answers a query");
    return result;
  }

 private:
  struct Node {
    Line line;
    std::unique_ptr<Node> left, right;
  };

  long long min_x_, max_x_;
  std::unique_ptr<Node> root_;

  static void add_line(std::unique_ptr<Node>& node, long long left, long long right, Line line) {
    if (!node) { node = std::make_unique<Node>(); node->line = line; return; }
    const long long middle = left + (right - left) / 2;
    const bool better_left = line.value(left) < node->line.value(left);
    const bool better_middle = line.value(middle) < node->line.value(middle);
    if (better_middle) std::swap(line, node->line);
    if (left == right) return;
    if (better_left != better_middle) add_line(node->left, left, middle, line);
    else add_line(node->right, middle + 1, right, line);
  }

  static long long query(const Node* node, long long left, long long right, long long x) {
    if (!node) return std::numeric_limits<long long>::max() / 4;
    long long result = node->line.value(x);
    if (left == right) return result;
    const long long middle = left + (right - left) / 2;
    if (x <= middle) return std::min(result, query(node->left.get(), left, middle, x));
    return std::min(result, query(node->right.get(), middle + 1, right, x));
  }
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Insert arbitrary lines and query their minimum on an integer domain."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  LiChaoTree tree(0, 10);
    tree.add_line(2, 3);
    tree.add_line(-1, 10);
    tree.add_line(0, 5);
    assert(tree.query(0) == 3);
    assert(tree.query(4) == 5);
    assert(tree.query(10) == 0);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
