// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/rollback_dsu

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

class RollbackDsu {
 public:
  explicit RollbackDsu(int n = 0) { reset(n); }

  void reset(int n) {
    n_ = (n < 0 ? 0 : n);
    components_ = n_;
    parent_.resize(n_);
    size_.assign(n_, 1);
    history_.clear();
    for (int i = 0; i < n_; ++i) {
      parent_[i] = i;
    }
    trace("Rollback DSU reset");
  }

  int size() const { return n_; }

  int components() const { return components_; }

  int find(int v) const {
    if (v < 0 || v >= n_) {
      return -1;
    }
    while (parent_[v] != v) {
      v = parent_[v];
    }
    return v;
  }

  bool same(int a, int b) const {
    const int root_a = find(a);
    const int root_b = find(b);
    return root_a != -1 && root_a == root_b;
  }

  int component_size(int v) const {
    const int root = find(v);
    return root == -1 ? 0 : size_[root];
  }

  int snapshot() const { return static_cast<int>(history_.size()); }

  bool unite(int a, int b) {
    int root_a = find(a);
    int root_b = find(b);
    if (root_a == -1 || root_b == -1 || root_a == root_b) {
      history_.push_back(Change{-1, -1, -1});
      trace("Rollback DSU rejected a union");
      return false;
    }
    if (size_[root_a] > size_[root_b]) {
      std::swap(root_a, root_b);
    }
    history_.push_back(Change{root_a, root_b, size_[root_b]});
    parent_[root_a] = root_b;
    size_[root_b] += size_[root_a];
    --components_;
    trace("Rollback DSU joined two components");
    return true;
  }

  void rollback() {
    if (history_.empty()) {
      return;
    }
    undo_one();
    trace("Rollback DSU undid one union");
  }

  void rollback(int snapshot_id) {
    if (snapshot_id < 0) {
      snapshot_id = 0;
    }
    while (static_cast<int>(history_.size()) > snapshot_id) {
      undo_one();
    }
    trace("Rollback DSU restored a snapshot");
  }

 private:
  struct Change {
    int child;
    int parent;
    int parent_size;
  };

  int n_;
  int components_;
  std::vector<int> parent_;
  std::vector<int> size_;
  std::vector<Change> history_;

  void trace(const char* label) const {
    EDULCNI_VIS(edulcni::live::forest("rollback_dsu.forest", parent_));
    EDULCNI_VIS(edulcni::live::array("rollback_dsu.sizes", size_));
    EDULCNI_VIS(edulcni::live::array(
        "rollback_dsu.components", std::vector<int>{components_}));
    EDULCNI_STEP(label);
  }

  void undo_one() {
    const Change change = history_.back();
    history_.pop_back();
    if (change.child == -1) {
      return;
    }
    parent_[change.child] = change.child;
    size_[change.parent] = change.parent_size;
    ++components_;
  }
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Merge components, then restore a previous DSU snapshot."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  RollbackDsu dsu(5);
    dsu.unite(0, 1);
    const int snapshot = dsu.snapshot();
    dsu.unite(1, 2);
    assert(dsu.same(0, 2));
    dsu.rollback(snapshot);
    assert(!dsu.same(0, 2));
    assert(dsu.same(0, 1));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
