// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/suffix_array

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

struct SuffixArrayResult {
  std::vector<int> sa;

  std::vector<int> lcp;


  std::vector<int> rank;

};

inline SuffixArrayResult suffix_array_build_from_positive_codes(
    const std::vector<int>& positive_codes, int alphabet_limit = 0) {
  const int text_n = static_cast<int>(positive_codes.size());
  const int n = text_n + 1;

  std::vector<int> sequence(n, 0);
  int lim = (alphabet_limit < 2 ? 2 : alphabet_limit);
  for (int i = 0; i < text_n; ++i) {
    const int code = (positive_codes[i] <= 0 ? 1 : positive_codes[i]);
    sequence[i] = code;
    if (code + 1 > lim) {
      lim = code + 1;
    }
  }

  SuffixArrayResult result;
  result.sa.assign(n, 0);

  result.lcp.assign(n, 0);


  result.rank.assign(n, 0);


  std::vector<int> x = sequence;
  std::vector<int> y(n, 0);
  std::vector<int> ws(std::max(n, lim), 0);
  std::iota(result.sa.begin(), result.sa.end(), 0);
  EDULCNI_VIS(edulcni::live::array("suffix_array.sequence", sequence));
  EDULCNI_STEP("Suffix array initialized");

  for (int j = 0, p = 0; p < n; j = std::max(1, j * 2), lim = p) {
    p = j;
    std::iota(y.begin(), y.end(), n - j);
    for (int i = 0; i < n; ++i) {
      if (result.sa[i] >= j) {
        y[p++] = result.sa[i] - j;
      }
    }

    std::fill(ws.begin(), ws.begin() + lim, 0);
    for (int i = 0; i < n; ++i) {
      ++ws[x[i]];
    }
    for (int i = 1; i < lim; ++i) {
      ws[i] += ws[i - 1];
    }
    for (int i = n - 1; i >= 0; --i) {
      result.sa[--ws[x[y[i]]]] = y[i];
    }

    std::swap(x, y);
    p = 1;
    x[result.sa[0]] = 0;
    for (int i = 1; i < n; ++i) {
      const int a = result.sa[i - 1];
      const int b = result.sa[i];
      const int a_second = (a + j < n ? y[a + j] : -1);
      const int b_second = (b + j < n ? y[b + j] : -1);
      x[b] = (y[a] == y[b] && a_second == b_second) ? p - 1 : p++;
    }
    EDULCNI_VIS(edulcni::live::array("suffix_array.order", result.sa));
    EDULCNI_VIS(edulcni::live::array("suffix_array.classes", x));
    EDULCNI_STEP("Suffix array completed a doubling round");
  }


  std::vector<int> rank(n, 0);
  for (int i = 0; i < n; ++i) {
    rank[result.sa[i]] = i;
  }

  result.rank = rank;





  for (int i = 0, k = 0; i < n - 1; ++i) {
    const int r = rank[i];
    const int j = result.sa[r - 1];
    while (i + k < n && j + k < n && sequence[i + k] == sequence[j + k]) {
      ++k;
    }
    result.lcp[r] = k;
    if (k > 0) {
      --k;
    }
  }



  EDULCNI_VIS(edulcni::live::array("suffix_array.order", result.sa));

  EDULCNI_VIS(edulcni::live::array("suffix_array.lcp", result.lcp));

  EDULCNI_STEP("Suffix array completed");

  return result;
}


inline SuffixArrayResult suffix_array_build(const std::string& s) {
  std::vector<int> codes(s.size(), 0);
  for (int i = 0; i < static_cast<int>(s.size()); ++i) {
    codes[i] = static_cast<int>(static_cast<unsigned char>(s[i])) + 1;
  }
  EDULCNI_VIS(edulcni::live::text("suffix_array.text", s));
  return suffix_array_build_from_positive_codes(codes, 257);
}





inline std::vector<int> suffix_array_remove_empty_suffix(
    const SuffixArrayResult& result) {
  if (result.sa.empty()) {
    return {};
  }
  const int empty_suffix_start = static_cast<int>(result.sa.size()) - 1;
  std::vector<int> stripped;
  stripped.reserve(result.sa.size() - 1);
  for (int start : result.sa) {
    if (start != empty_suffix_start) {
      stripped.push_back(start);
    }
  }
  return stripped;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  const std::string text = "banana";
    const auto result = suffix_array_build(text);
    assert((result.sa == std::vector<int>{6, 5, 3, 1, 0, 4, 2}));
    assert((result.lcp == std::vector<int>{0, 0, 1, 3, 0, 0, 2}));
    const auto without_empty = suffix_array_remove_empty_suffix(result);
    assert((without_empty == std::vector<int>{5, 3, 1, 0, 4, 2}));

  cout << "ok\n";
  return 0;
}
