// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/potential_dsu

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <class Value>
class PotentialDsu {
 public:
  explicit PotentialDsu(int n = 0) : parent_(n, -1), to_parent_(n, Value{}) {}

  std::pair<int, Value> find(int vertex) {
    if (parent_[vertex] < 0) return {vertex, Value{}};
    auto [root, value] = find(parent_[vertex]);
    to_parent_[vertex] += value;
    parent_[vertex] = root;
    return {root, to_parent_[vertex]};
  }

  // Adds the constraint potential(b) - potential(a) = difference.
  bool unite(int a, int b, Value difference) {
    auto [root_a, value_a] = find(a);
    auto [root_b, value_b] = find(b);
    if (root_a == root_b) return value_b - value_a == difference;
    Value root_difference = difference + value_a - value_b;
    if (parent_[root_a] > parent_[root_b]) {
      std::swap(root_a, root_b);
      root_difference = -root_difference;
    }
    parent_[root_a] += parent_[root_b];
    parent_[root_b] = root_a;
    to_parent_[root_b] = root_difference;
    return true;
  }

  std::optional<Value> difference(int a, int b) {
    auto [root_a, value_a] = find(a);
    auto [root_b, value_b] = find(b);
    if (root_a != root_b) return std::nullopt;
    return value_b - value_a;
  }

 private:
  std::vector<int> parent_;
  std::vector<Value> to_parent_;
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Maintain relative potentials and reject inconsistent constraints."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  PotentialDsu<long long> dsu(4);
    assert(dsu.unite(0, 1, 5));
    assert(dsu.unite(1, 2, -2));
    assert(dsu.difference(0, 2) == std::optional<long long>{3});
    assert(!dsu.unite(0, 2, 4));
    assert(!dsu.difference(0, 3).has_value());

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
