// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/geometry

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename T>
int geometry_sign(const T& value) {
  return (T(0) < value) - (value < T(0));
}


inline int geometry_sign_eps(long double value, long double eps = 1e-12L) {
  return (value > eps) - (value < -eps);
}

template <typename T>
struct Point2 {
  using Value = T;
  T x;
  T y;

  Point2(const T& x_ = T(), const T& y_ = T()) : x(x_), y(y_) {}

  bool operator==(const Point2& other) const {
    return x == other.x && y == other.y;
  }

  bool operator!=(const Point2& other) const { return !(*this == other); }

  bool operator<(const Point2& other) const {
    if (x != other.x) {
      return x < other.x;
    }
    return y < other.y;
  }

  Point2 operator+(const Point2& other) const {
    return Point2(x + other.x, y + other.y);
  }

  Point2 operator-(const Point2& other) const {
    return Point2(x - other.x, y - other.y);
  }

  Point2 operator*(const T& scale) const { return Point2(x * scale, y * scale); }

  Point2 operator/(const T& scale) const { return Point2(x / scale, y / scale); }

  T dot(const Point2& other) const { return x * other.x + y * other.y; }

  T cross(const Point2& other) const { return x * other.y - y * other.x; }

  T cross(const Point2& a, const Point2& b) const { return (a - *this).cross(b - *this); }

  T norm2() const { return x * x + y * y; }

  friend std::istream& operator>>(std::istream& in, Point2& point) {
    return in >> point.x >> point.y;
  }

  friend std::ostream& operator<<(std::ostream& out, const Point2& point) {
    return out << point.x << ' ' << point.y;
  }
};



template <typename T>
inline long double cross_ld(const Point2<T>& a, const Point2<T>& b) {
  return static_cast<long double>(a.x) * static_cast<long double>(b.y) -
         static_cast<long double>(a.y) * static_cast<long double>(b.x);
}

template <typename T>
inline long double cross_ld(const Point2<T>& a, const Point2<T>& b,
                            const Point2<T>& c) {
  return cross_ld(b - a, c - a);
}


template <typename T>
inline int orientation(const Point2<T>& a, const Point2<T>& b, const Point2<T>& c,
                       long double eps = 1e-12L) {
  return geometry_sign_eps(cross_ld(a, b, c), eps);
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Intersect segments and construct a convex hull."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  using Point = Point2<long long>;
    assert(segments_intersect(Point(0, 0), Point(2, 2), Point(0, 2), Point(2, 0)));
    const auto intersections = segment_intersection(
        Point(0, 0), Point(2, 2), Point(0, 2), Point(2, 0));
    assert(intersections.size() == 1);
    std::vector<Point> points = {
        Point(0, 0), Point(2, 0), Point(2, 2), Point(0, 2), Point(1, 1)};
    const std::vector<Point> hull = convex_hull(points);
    assert((hull == std::vector<Point>{Point(0, 0), Point(2, 0), Point(2, 2), Point(0, 2)}));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
