// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/geometry

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

inline int geometry_sign_eps(long double value, long double eps = 1e-12L) {
  return (value > eps) - (value < -eps);
}

template <typename T>
struct Point2 {
  using Value = T;
  T x;
  T y;

  Point2(const T& x_ = T(), const T& y_ = T()) : x(x_), y(y_) {}

  bool operator==(const Point2& other) const {
    return x == other.x && y == other.y;
  }

  bool operator!=(const Point2& other) const { return !(*this == other); }

  bool operator<(const Point2& other) const {
    if (x != other.x) {
      return x < other.x;
    }
    return y < other.y;
  }

  Point2 operator+(const Point2& other) const {
    return Point2(x + other.x, y + other.y);
  }

  Point2 operator-(const Point2& other) const {
    return Point2(x - other.x, y - other.y);
  }

  Point2 operator*(const T& scale) const { return Point2(x * scale, y * scale); }

  Point2 operator/(const T& scale) const { return Point2(x / scale, y / scale); }

  T dot(const Point2& other) const { return x * other.x + y * other.y; }

  T cross(const Point2& other) const { return x * other.y - y * other.x; }

  T cross(const Point2& a, const Point2& b) const { return (a - *this).cross(b - *this); }

  T norm2() const { return x * x + y * y; }

  friend std::istream& operator>>(std::istream& in, Point2& point) {
    return in >> point.x >> point.y;
  }

  friend std::ostream& operator<<(std::ostream& out, const Point2& point) {
    return out << point.x << ' ' << point.y;
  }
};



template <typename T>
inline long double cross_ld(const Point2<T>& a, const Point2<T>& b) {
  return static_cast<long double>(a.x) * static_cast<long double>(b.y) -
         static_cast<long double>(a.y) * static_cast<long double>(b.x);
}

template <typename T>
inline long double cross_ld(const Point2<T>& a, const Point2<T>& b,
                            const Point2<T>& c) {
  return cross_ld(b - a, c - a);
}








template <typename T>
inline std::vector<Point2<T>> convex_hull(std::vector<Point2<T>> points,
                                          long double eps = 1e-12L) {
  EDULCNI_VIS(edulcni::live::points("convex_hull.points", points));
  EDULCNI_STEP("Convex hull initialized");
  if (points.size() <= 1) {
    return points;
  }

  std::sort(points.begin(), points.end());
  points.erase(std::unique(points.begin(), points.end()), points.end());
  if (points.size() <= 1) {
    return points;
  }

  std::vector<Point2<T>> lower;
  std::vector<Point2<T>> upper;

  for (const Point2<T>& p : points) {
    while (lower.size() >= 2 &&
           geometry_sign_eps(cross_ld(lower[lower.size() - 2], lower.back(), p), eps) <=
               0) {
      lower.pop_back();
    }
    lower.push_back(p);
    EDULCNI_VIS(edulcni::live::points("convex_hull.chain", lower));
    EDULCNI_VIS(edulcni::live::points_focus(
        "convex_hull.points", std::vector<Point2<T>>{p},
        edulcni::live::FocusRole::accepted,
        "accepted on the lower hull"));
    EDULCNI_STEP("Convex hull extends the lower chain");
  }

  for (int i = static_cast<int>(points.size()) - 1; i >= 0; --i) {
    const Point2<T>& p = points[i];
    while (upper.size() >= 2 &&
           geometry_sign_eps(cross_ld(upper[upper.size() - 2], upper.back(), p), eps) <=
               0) {
      upper.pop_back();
    }
    upper.push_back(p);
    EDULCNI_VIS(edulcni::live::points("convex_hull.chain", upper));
    EDULCNI_VIS(edulcni::live::points_focus(
        "convex_hull.points", std::vector<Point2<T>>{p},
        edulcni::live::FocusRole::accepted,
        "accepted on the upper hull"));
    EDULCNI_STEP("Convex hull extends the upper chain");
  }

  lower.pop_back();
  upper.pop_back();
  lower.insert(lower.end(), upper.begin(), upper.end());
  EDULCNI_VIS(edulcni::live::points("convex_hull.chain", lower));
  EDULCNI_VIS(edulcni::live::points_focus(
      "convex_hull.points", lower, edulcni::live::FocusRole::result,
      "points on the convex hull"));
  EDULCNI_STEP("Convex hull completed");
  return lower;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Construct a convex hull from a small point set."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  using Point = Point2<long long>;
    std::vector<Point> points = {
        Point(0, 0), Point(2, 0), Point(2, 2), Point(0, 2), Point(1, 1)};
    const std::vector<Point> hull = convex_hull(points);
    assert((hull == std::vector<Point>{Point(0, 0), Point(2, 0), Point(2, 2), Point(0, 2)}));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
