// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/monotonic_stack

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename T, typename Compare>
inline std::vector<int> nearest_left_by(const std::vector<T>& values,
                                        Compare compare, bool strict = true) {
  const int n = static_cast<int>(values.size());
  std::vector<int> result(n, -1);
  std::vector<int> st;
  st.reserve(n);

  for (int i = 0; i < n; ++i) {
    while (!st.empty()) {
      const int j = st.back();
      const bool keep = strict ? compare(values[j], values[i])
                               : !compare(values[i], values[j]);
      if (keep) {
        break;
      }
      st.pop_back();
    }
    if (!st.empty()) {
      result[i] = st.back();
    }
    st.push_back(i);
    EDULCNI_VIS(edulcni::live::array("monotonic_stack.values", values));
    EDULCNI_VIS(edulcni::live::array("monotonic_stack.indices", st));
    EDULCNI_VIS(edulcni::live::array("monotonic_stack.answer", result));
    EDULCNI_STEP("Monotonic stack processed an element from the left");
  }
  return result;
}

template <typename T, typename Compare>
inline std::vector<int> nearest_right_by(const std::vector<T>& values,
                                         Compare compare, bool strict = true) {
  const int n = static_cast<int>(values.size());
  std::vector<int> result(n, -1);
  std::vector<int> st;
  st.reserve(n);

  for (int i = n - 1; i >= 0; --i) {
    while (!st.empty()) {
      const int j = st.back();
      const bool keep = strict ? compare(values[j], values[i])
                               : !compare(values[i], values[j]);
      if (keep) {
        break;
      }
      st.pop_back();
    }
    if (!st.empty()) {
      result[i] = st.back();
    }
    st.push_back(i);
    EDULCNI_VIS(edulcni::live::array("monotonic_stack.values", values));
    EDULCNI_VIS(edulcni::live::array("monotonic_stack.indices", st));
    EDULCNI_VIS(edulcni::live::array("monotonic_stack.answer", result));
    EDULCNI_STEP("Monotonic stack processed an element from the right");
  }
  return result;
}

template <typename T>
inline std::vector<int> nearest_smaller_left(const std::vector<T>& values,
                                             bool strict = true) {
  return nearest_left_by(values, std::less<T>(), strict);
}

template <typename T>
inline std::vector<int> nearest_smaller_right(const std::vector<T>& values,
                                              bool strict = true) {
  return nearest_right_by(values, std::less<T>(), strict);
}

template <typename T>
inline std::vector<int> nearest_greater_left(const std::vector<T>& values,
                                             bool strict = true) {
  return nearest_left_by(values, std::greater<T>(), strict);
}

template <typename T>
inline std::vector<int> nearest_greater_right(const std::vector<T>& values,
                                              bool strict = true) {
  return nearest_right_by(values, std::greater<T>(), strict);
}

template <typename T>
struct NearestIndices {
  std::vector<int> left_smaller;
  std::vector<int> right_smaller;
  std::vector<int> left_greater;
  std::vector<int> right_greater;
};

template <typename T>
inline NearestIndices<T> nearest_all(const std::vector<T>& values,
                                     bool strict = true) {
  NearestIndices<T> result;
  result.left_smaller = nearest_smaller_left(values, strict);
  result.right_smaller = nearest_smaller_right(values, strict);
  result.left_greater = nearest_greater_left(values, strict);
  result.right_greater = nearest_greater_right(values, strict);
  return result;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Find the nearest smaller and greater elements on both sides."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  const std::vector<int> values = {5, 2, 4, 4, 1, 3};
    const auto nearest = nearest_all(values, true);
    assert((nearest.left_smaller == std::vector<int>{-1, -1, 1, 1, -1, 4}));
    assert((nearest.right_greater == std::vector<int>{-1, 2, -1, -1, 5, -1}));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
