// Generated by scripts/sync-library.mjs. Do not edit.
export const DIRECT_COMMANDS = [
  {
    "command": "edulcni.segtree",
    "snippetPath": "/templates/segtree"
  },
  {
    "command": "edulcni.berlekamp_massey",
    "snippetPath": "/templates/berlekamp_massey"
  },
  {
    "command": "edulcni.sparse_table",
    "snippetPath": "/templates/sparse_table"
  },
  {
    "command": "edulcni.modpow",
    "snippetPath": "/templates/modpow"
  },
  {
    "command": "edulcni.bfs",
    "snippetPath": "/templates/bfs"
  },
  {
    "command": "edulcni.linear_sieve",
    "snippetPath": "/templates/linear_sieve"
  },
  {
    "command": "edulcni.fenwick",
    "snippetPath": "/templates/fenwick"
  },
  {
    "command": "edulcni.factorial_precalc",
    "snippetPath": "/templates/factorial_precalc"
  },
  {
    "command": "edulcni.powers_precalc",
    "snippetPath": "/templates/powers_precalc"
  },
  {
    "command": "edulcni.modint",
    "snippetPath": "/templates/modint"
  },
  {
    "command": "edulcni.compress_unique",
    "snippetPath": "/templates/compress_unique"
  },
  {
    "command": "edulcni.input",
    "snippetPath": "/templates/input"
  },
  {
    "command": "edulcni.connected_components",
    "snippetPath": "/templates/connected_components"
  },
  {
    "command": "edulcni.dsu",
    "snippetPath": "/templates/dsu"
  },
  {
    "command": "edulcni.rollback_dsu",
    "snippetPath": "/templates/rollback_dsu"
  },
  {
    "command": "edulcni.lca",
    "snippetPath": "/templates/lca"
  },
  {
    "command": "edulcni.twosat",
    "snippetPath": "/templates/twosat"
  },
  {
    "command": "edulcni.maxflow_dinic",
    "snippetPath": "/templates/maxflow_dinic"
  },
  {
    "command": "edulcni.mincost_maxflow",
    "snippetPath": "/templates/mincost_maxflow"
  },
  {
    "command": "edulcni.hungarian",
    "snippetPath": "/templates/hungarian"
  },
  {
    "command": "edulcni.kuhn",
    "snippetPath": "/templates/kuhn"
  },
  {
    "command": "edulcni.implicit_treap",
    "snippetPath": "/templates/implicit_treap"
  },
  {
    "command": "edulcni.merge_sort_tree",
    "snippetPath": "/templates/merge_sort_tree"
  },
  {
    "command": "edulcni.poly_hash",
    "snippetPath": "/templates/poly_hash"
  },
  {
    "command": "edulcni.suffix_array",
    "snippetPath": "/templates/suffix_array"
  },
  {
    "command": "edulcni.segtree_beats",
    "snippetPath": "/templates/segtree_beats"
  },
  {
    "command": "edulcni.fft_ntt",
    "snippetPath": "/templates/fft_ntt"
  },
  {
    "command": "edulcni.fast_allocator",
    "snippetPath": "/templates/fast_allocator"
  },
  {
    "command": "edulcni.object_pool",
    "snippetPath": "/templates/object_pool"
  },
  {
    "command": "edulcni.monotonic_stack",
    "snippetPath": "/templates/monotonic_stack"
  },
  {
    "command": "edulcni.toposort",
    "snippetPath": "/templates/toposort"
  },
  {
    "command": "edulcni.kosaraju",
    "snippetPath": "/templates/kosaraju"
  },
  {
    "command": "edulcni.dijkstra",
    "snippetPath": "/templates/dijkstra"
  },
  {
    "command": "edulcni.gp_hash_table",
    "snippetPath": "/templates/gp_hash_table"
  },
  {
    "command": "edulcni.ordered_set",
    "snippetPath": "/templates/ordered_set"
  },
  {
    "command": "edulcni.set_utils",
    "snippetPath": "/templates/set_utils"
  },
  {
    "command": "edulcni.hld",
    "snippetPath": "/templates/hld"
  },
  {
    "command": "edulcni.mo",
    "snippetPath": "/templates/mo"
  },
  {
    "command": "edulcni.geometry",
    "snippetPath": "/templates/geometry"
  },
  {
    "command": "edulcni.halfplane_intersection",
    "snippetPath": "/templates/halfplane_intersection"
  },
  {
    "command": "edulcni.base_template",
    "snippetPath": "/templates/base_template"
  },
  {
    "command": "edulcni.bfs_dist",
    "snippetPath": "/templates/bfs_dist"
  },
  {
    "command": "edulcni.bitmask_loop",
    "snippetPath": "/templates/bitmask_loop"
  },
  {
    "command": "edulcni.block_lengths",
    "snippetPath": "/templates/block_lengths"
  },
  {
    "command": "edulcni.decrement_indices",
    "snippetPath": "/templates/decrement_indices"
  },
  {
    "command": "edulcni.dfs_tree",
    "snippetPath": "/templates/dfs_tree"
  },
  {
    "command": "edulcni.dsu_short",
    "snippetPath": "/templates/dsu_short"
  },
  {
    "command": "edulcni.fenwick_sum",
    "snippetPath": "/templates/fenwick_sum"
  },
  {
    "command": "edulcni.grid4",
    "snippetPath": "/templates/grid4"
  },
  {
    "command": "edulcni.lower_bound_l_false_r_true",
    "snippetPath": "/templates/lower_bound_l_false_r_true"
  },
  {
    "command": "edulcni.prefix_2d",
    "snippetPath": "/templates/prefix_2d"
  },
  {
    "command": "edulcni.print_vector",
    "snippetPath": "/templates/print_vector"
  },
  {
    "command": "edulcni.static_rsq",
    "snippetPath": "/templates/static_rsq"
  },
  {
    "command": "edulcni.test_generators",
    "snippetPath": "/templates/test_generators"
  },
  {
    "command": "edulcni.stress_test",
    "snippetPath": "/templates/stress_test"
  },
  {
    "command": "edulcni.interactive_query",
    "snippetPath": "/templates/interactive_query"
  },
  {
    "command": "edulcni.tree_hash",
    "snippetPath": "/templates/tree_hash"
  },
  {
    "command": "edulcni.submasks",
    "snippetPath": "/templates/submasks"
  },
  {
    "command": "edulcni.proper_submasks",
    "snippetPath": "/templates/proper_submasks"
  },
  {
    "command": "edulcni.supermasks",
    "snippetPath": "/templates/supermasks"
  },
  {
    "command": "edulcni.subset_partitions",
    "snippetPath": "/templates/subset_partitions"
  },
  {
    "command": "edulcni.disjoint_masks",
    "snippetPath": "/templates/disjoint_masks"
  },
  {
    "command": "edulcni.subset_zeta",
    "snippetPath": "/templates/subset_zeta"
  },
  {
    "command": "edulcni.subset_mobius",
    "snippetPath": "/templates/subset_mobius"
  },
  {
    "command": "edulcni.kruskal",
    "snippetPath": "/templates/kruskal"
  },
  {
    "command": "edulcni.fwt_convolution",
    "snippetPath": "/templates/fwt_convolution"
  },
  {
    "command": "edulcni.offline_dynamic_connectivity",
    "snippetPath": "/templates/offline_dynamic_connectivity"
  },
  {
    "command": "edulcni.dp_knapsack",
    "snippetPath": "/templates/dp_knapsack"
  },
  {
    "command": "edulcni.lis",
    "snippetPath": "/templates/lis"
  },
  {
    "command": "edulcni.digit_dp",
    "snippetPath": "/templates/digit_dp"
  },
  {
    "command": "edulcni.sos_dp",
    "snippetPath": "/templates/sos_dp"
  },
  {
    "command": "edulcni.turtle_dp",
    "snippetPath": "/templates/turtle_dp"
  },
  {
    "command": "edulcni.substring_dp",
    "snippetPath": "/templates/substring_dp"
  },
  {
    "command": "edulcni.divide_conquer_dp",
    "snippetPath": "/templates/divide_conquer_dp"
  },
  {
    "command": "edulcni.knuth_dp",
    "snippetPath": "/templates/knuth_dp"
  },
  {
    "command": "edulcni.convex_hull_trick",
    "snippetPath": "/templates/convex_hull_trick"
  },
  {
    "command": "edulcni.li_chao_tree",
    "snippetPath": "/templates/li_chao_tree"
  },
  {
    "command": "edulcni.monotone_queue_dp",
    "snippetPath": "/templates/monotone_queue_dp"
  },
  {
    "command": "edulcni.aliens_trick",
    "snippetPath": "/templates/aliens_trick"
  },
  {
    "command": "edulcni.output",
    "snippetPath": "/templates/output"
  },
  {
    "command": "edulcni.first_true",
    "snippetPath": "/templates/first_true"
  },
  {
    "command": "edulcni.difference_array",
    "snippetPath": "/templates/difference_array"
  },
  {
    "command": "edulcni.sliding_window_max",
    "snippetPath": "/templates/sliding_window_max"
  },
  {
    "command": "edulcni.zero_one_bfs",
    "snippetPath": "/templates/zero_one_bfs"
  },
  {
    "command": "edulcni.bridges",
    "snippetPath": "/templates/bridges"
  },
  {
    "command": "edulcni.tree_diameter",
    "snippetPath": "/templates/tree_diameter"
  },
  {
    "command": "edulcni.euler_subtrees",
    "snippetPath": "/templates/euler_subtrees"
  },
  {
    "command": "edulcni.z_function",
    "snippetPath": "/templates/z_function"
  },
  {
    "command": "edulcni.manacher",
    "snippetPath": "/templates/manacher"
  },
  {
    "command": "edulcni.xor_basis",
    "snippetPath": "/templates/xor_basis"
  },
  {
    "command": "edulcni.bitset_knapsack",
    "snippetPath": "/templates/bitset_knapsack"
  },
  {
    "command": "edulcni.persistent_segment_tree",
    "snippetPath": "/templates/persistent_segment_tree"
  },
  {
    "command": "edulcni.binary_trie",
    "snippetPath": "/templates/binary_trie"
  },
  {
    "command": "edulcni.crt",
    "snippetPath": "/templates/crt"
  },
  {
    "command": "edulcni.primality_64",
    "snippetPath": "/templates/primality_64"
  },
  {
    "command": "edulcni.factorization_64",
    "snippetPath": "/templates/factorization_64"
  },
  {
    "command": "edulcni.minimum_rotation",
    "snippetPath": "/templates/minimum_rotation"
  },
  {
    "command": "edulcni.euler_walk",
    "snippetPath": "/templates/euler_walk"
  },
  {
    "command": "edulcni.floyd_warshall",
    "snippetPath": "/templates/floyd_warshall"
  },
  {
    "command": "edulcni.hopcroft_karp",
    "snippetPath": "/templates/hopcroft_karp"
  },
  {
    "command": "edulcni.global_min_cut",
    "snippetPath": "/templates/global_min_cut"
  },
  {
    "command": "edulcni.geometry_point",
    "snippetPath": "/templates/geometry_point"
  },
  {
    "command": "edulcni.closest_pair",
    "snippetPath": "/templates/closest_pair"
  },
  {
    "command": "edulcni.minimum_enclosing_circle",
    "snippetPath": "/templates/minimum_enclosing_circle"
  },
  {
    "command": "edulcni.circle_intersection",
    "snippetPath": "/templates/circle_intersection"
  },
  {
    "command": "edulcni.polygon_cut",
    "snippetPath": "/templates/polygon_cut"
  },
  {
    "command": "edulcni.hull_diameter",
    "snippetPath": "/templates/hull_diameter"
  },
  {
    "command": "edulcni.solve_linear",
    "snippetPath": "/templates/solve_linear"
  },
  {
    "command": "edulcni.determinant",
    "snippetPath": "/templates/determinant"
  },
  {
    "command": "edulcni.golden_section",
    "snippetPath": "/templates/golden_section"
  },
  {
    "command": "edulcni.interval_set",
    "snippetPath": "/templates/interval_set"
  },
  {
    "command": "edulcni.constant_intervals",
    "snippetPath": "/templates/constant_intervals"
  },
  {
    "command": "edulcni.permutation_rank",
    "snippetPath": "/templates/permutation_rank"
  }
] as const;
