// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/floor_sum

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

inline __int128 floor_sum_unsigned(long long count, long long modulus,
                                   long long multiplier, long long offset) {
  __int128 answer = 0;
  while (true) {
    if (multiplier >= modulus) {
      answer += (__int128)(count - 1) * count * (multiplier / modulus) / 2;
      multiplier %= modulus;
    }
    if (offset >= modulus) {
      answer += (__int128)count * (offset / modulus);
      offset %= modulus;
    }
    const __int128 maximum = (__int128)multiplier * count + offset;
    if (maximum < modulus) return answer;
    count = static_cast<long long>(maximum / modulus);
    offset = static_cast<long long>(maximum % modulus);
    std::swap(modulus, multiplier);
  }
}

inline __int128 floor_sum(long long count, long long modulus,
                          long long multiplier, long long offset) {
  if (count <= 0 || modulus <= 0) return 0;
  __int128 answer = 0;
  if (multiplier < 0) {
    const long long quotient = multiplier / modulus - (multiplier % modulus != 0);
    answer += (__int128)(count - 1) * count * quotient / 2;
    multiplier %= modulus;
    if (multiplier < 0) multiplier += modulus;
  }
  if (offset < 0) {
    const long long quotient = offset / modulus - (offset % modulus != 0);
    answer += (__int128)count * quotient;
    offset %= modulus;
    if (offset < 0) offset += modulus;
  }
  return answer + floor_sum_unsigned(count, modulus, multiplier, offset);
}

inline __int128 count_lattice_points_below(long long x_count, long long denominator,
                                            long long slope_numerator,
                                            long long intercept_numerator) {
  if (x_count <= 0 || denominator <= 0) return 0;
  return floor_sum(x_count, denominator, slope_numerator,
                   intercept_numerator) + x_count;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Evaluate signed floor sums and lattice-point counts."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  assert(floor_sum(5, 7, 3, 2) == 4);
    assert(floor_sum(4, 5, -2, 1) == -3);
    assert(count_lattice_points_below(5, 7, 3, 2) == 9);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
