// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/set_utils

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename Container, typename Key>
inline std::optional<typename Container::value_type> next_value(
    const Container& container, const Key& key) {
  const auto it = container.upper_bound(key);
  if (it == container.end()) {
    return std::nullopt;
  }
  EDULCNI_VIS(edulcni::live::array("set_utils.container", container));
  EDULCNI_STEP("Set utility found the next value");
  return *it;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Safely inspect neighboring values in ordered containers."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  const std::set<int> values = {2, 4, 8};
    assert(next_value(values, 4).value() == 8);
    assert(prev_value(values, 4).value() == 2);
    assert(!next_value(values, 8).has_value());
    assert(!prev_value(values, 2).has_value());

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
