// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/mincost_maxflow

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename Cap, typename Cost>
class MinCostMaxFlow {
 public:
  struct Edge {
    int to;
    int rev;
    Cap cap;
    Cost cost;
    Cap original_cap;

    Edge(int to_ = 0, int rev_ = 0, Cap cap_ = Cap(0), Cost cost_ = Cost(0),
         Cap original_cap_ = Cap(0))
        : to(to_),
          rev(rev_),
          cap(cap_),
          cost(cost_),
          original_cap(original_cap_) {}

    Cap flow() const { return original_cap - cap; }
  };

  explicit MinCostMaxFlow(int n = 0)
      : n_(0), has_negative_cost_edge_(false), potentials_initialized_(false) {
    reset(n);
  }

  void reset(int n) {
    n_ = (n < 0 ? 0 : n);
    graph_.assign(n_, std::vector<Edge>());
    potential_.assign(n_, Cost(0));
    dist_.assign(n_, inf_cost());
    prev_vertex_.assign(n_, -1);
    prev_edge_.assign(n_, -1);
    has_negative_cost_edge_ = false;
    potentials_initialized_ = false;
    trace("Minimum-cost flow reset");
  }

  int size() const { return n_; }

  int add_edge(int from, int to, Cap cap, Cost cost) {
    return add_edge(from, to, cap, cost, Cap(0), -cost);
  }

  int add_edge(int from, int to, Cap cap, Cost cost, Cap rev_cap) {
    return add_edge(from, to, cap, cost, rev_cap, -cost);
  }

  int add_edge(int from, int to, Cap cap, Cost cost, Cap rev_cap, Cost rev_cost) {
    if (!vertex_ok(from) || !vertex_ok(to) || cap < Cap(0) || rev_cap < Cap(0)) {
      return -1;
    }

    const int from_id = static_cast<int>(graph_[from].size());
    const int to_id = static_cast<int>(graph_[to].size());
    graph_[from].push_back(Edge(to, to_id, cap, cost, cap));
    graph_[to].push_back(Edge(from, from_id, rev_cap, rev_cost, rev_cap));
    if ((cap > Cap(0) && cost < Cost(0)) || (rev_cap > Cap(0) && rev_cost < Cost(0))) {
      has_negative_cost_edge_ = true;
    }
    potentials_initialized_ = false;
    trace("Minimum-cost flow edge added");
    return from_id;
  }





  std::pair<Cap, Cost> min_cost_flow(
      int source, int sink,
      Cap flow_limit = std::numeric_limits<Cap>::max() / Cap(4)) {
    if (!vertex_ok(source) || !vertex_ok(sink) || source == sink ||
        flow_limit <= Cap(0)) {
      return std::make_pair(Cap(0), Cost(0));
    }

    if (has_negative_cost_edge_ && !potentials_initialized_) {
      bellman_ford_initialize(source);
      potentials_initialized_ = true;
    }
    if (!has_negative_cost_edge_ && !potentials_initialized_) {
      std::fill(potential_.begin(), potential_.end(), Cost(0));
      potentials_initialized_ = true;
    }

    Cap total_flow = Cap(0);
    Cost total_cost = Cost(0);
    trace("Minimum-cost flow initialized");

    while (total_flow < flow_limit && dijkstra(source, sink)) {
      Cap pushed = flow_limit - total_flow;
      for (int v = sink; v != source; v = prev_vertex_[v]) {
        const Edge& edge = graph_[prev_vertex_[v]][prev_edge_[v]];
        pushed = std::min(pushed, edge.cap);
      }

      for (int v = sink; v != source; v = prev_vertex_[v]) {
        Edge& edge = graph_[prev_vertex_[v]][prev_edge_[v]];
        Edge& rev = graph_[edge.to][edge.rev];
        edge.cap -= pushed;
        rev.cap += pushed;
        total_cost += static_cast<Cost>(pushed) * edge.cost;
      }
      total_flow += pushed;
      EDULCNI_VIS(edulcni::live::weighted_graph("mincost_flow.residual", graph_));
      EDULCNI_VIS(edulcni::live::array("mincost_flow.potential", potential_));
      EDULCNI_VIS(edulcni::live::array("mincost_flow.distance", dist_));
      EDULCNI_VIS(edulcni::live::array(
          "mincost_flow.total_flow", std::vector<Cap>{total_flow}));
      EDULCNI_VIS(edulcni::live::array(
          "mincost_flow.total_cost", std::vector<Cost>{total_cost}));
      EDULCNI_STEP("Minimum-cost flow augmented");
    }

    trace("Minimum-cost flow completed");
    return std::make_pair(total_flow, total_cost);
  }

  std::pair<Cap, Cost> max_flow_min_cost(int source, int sink) {
    return min_cost_flow(source, sink);
  }

  std::pair<Cap, Cost> min_cost_max_flow(int source, int sink) {
    return min_cost_flow(source, sink);
  }

 private:
  int n_;
  std::vector<std::vector<Edge>> graph_;
  std::vector<Cost> potential_;
  std::vector<Cost> dist_;
  std::vector<int> prev_vertex_;
  std::vector<int> prev_edge_;
  bool has_negative_cost_edge_;
  bool potentials_initialized_;

  void trace(const char* label) const {
    EDULCNI_VIS(edulcni::live::weighted_graph("mincost_flow.residual", graph_));
    EDULCNI_VIS(edulcni::live::array("mincost_flow.potential", potential_));
    EDULCNI_STEP(label);
  }

  bool vertex_ok(int v) const { return v >= 0 && v < n_; }

  static Cost inf_cost() { return std::numeric_limits<Cost>::max() / Cost(4); }

  void bellman_ford_initialize(int source) {
    const Cost inf = inf_cost();
    std::fill(potential_.begin(), potential_.end(), inf);
    potential_[source] = Cost(0);

    for (int it = 0; it < n_ - 1; ++it) {
      bool updated = false;
      for (int v = 0; v < n_; ++v) {
        if (potential_[v] == inf) {
          continue;
        }
        for (const Edge& edge : graph_[v]) {
          if (edge.cap <= Cap(0)) {
            continue;
          }
          const Cost candidate = potential_[v] + edge.cost;
          if (candidate < potential_[edge.to]) {
            potential_[edge.to] = candidate;
            updated = true;
          }
        }
      }
      if (!updated) {
        break;
      }
    }

    for (Cost& value : potential_) {
      if (value == inf) {
        value = Cost(0);
      }
    }
  }

  bool dijkstra(int source, int sink) {
    const Cost inf = inf_cost();
    std::fill(dist_.begin(), dist_.end(), inf);
    std::fill(prev_vertex_.begin(), prev_vertex_.end(), -1);
    std::fill(prev_edge_.begin(), prev_edge_.end(), -1);

    using Node = std::pair<Cost, int>;
    std::priority_queue<Node, std::vector<Node>, std::greater<Node>> pq;
    dist_[source] = Cost(0);
    pq.push(std::make_pair(Cost(0), source));

    while (!pq.empty()) {
      const Cost current_dist = pq.top().first;
      const int v = pq.top().second;
      pq.pop();
      if (current_dist != dist_[v]) {
        continue;
      }

      for (int edge_id = 0; edge_id < static_cast<int>(graph_[v].size()); ++edge_id) {
        const Edge& edge = graph_[v][edge_id];
        if (edge.cap <= Cap(0)) {
          continue;
        }

        const Cost reduced_cost = edge.cost + potential_[v] - potential_[edge.to];
        const Cost candidate = current_dist + reduced_cost;
        if (candidate < dist_[edge.to]) {
          dist_[edge.to] = candidate;
          prev_vertex_[edge.to] = v;
          prev_edge_[edge.to] = edge_id;
          pq.push(std::make_pair(candidate, edge.to));
        }
      }
    }

    if (dist_[sink] == inf) {
      return false;
    }
    for (int v = 0; v < n_; ++v) {
      if (dist_[v] != inf) {
        potential_[v] += dist_[v];
      }
    }
    return true;
  }
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Send maximum flow while minimizing its total edge cost."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  MinCostMaxFlow<long long, long long> flow(4);
    flow.add_edge(0, 1, 2, 1);
    flow.add_edge(0, 2, 1, 5);
    flow.add_edge(1, 2, 1, 2);
    flow.add_edge(1, 3, 1, 3);
    flow.add_edge(2, 3, 2, 1);
    const auto result = flow.min_cost_max_flow(0, 3);
    assert(result.first == 3);
    assert(result.second == 14);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
