// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/sparse_table

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

vector<int> sparse_log;

void ensure_sparse_log(int n) {
  if (static_cast<int>(sparse_log.size()) > n) {
    return;
  }
  int start = static_cast<int>(sparse_log.size());
  if (start < 2) {
    start = 2;
  }
  sparse_log.resize(n + 1, 0);
  for (int i = start; i <= n; ++i) {
    sparse_log[i] = sparse_log[i / 2] + 1;
  }
}

vector<vector<int>> sparse_min;

void build_sparse_min(const vector<int>& values) {
  const int n = static_cast<int>(values.size());
  ensure_sparse_log(n);
  sparse_min.clear();
  if (n == 0) {
    EDULCNI_VIS(edulcni::live::matrix("sparse_table.table", sparse_min));
    EDULCNI_STEP("Sparse table built");
    return;
  }

  sparse_min.assign(sparse_log[n] + 1, vector<int>());
  sparse_min[0] = values;
  for (int level = 1; level < static_cast<int>(sparse_min.size()); ++level) {
    const int len = 1 << level;
    const int half = len >> 1;
    sparse_min[level].assign(n - len + 1, int());
    for (int i = 0; i + len <= n; ++i) {
      const int& lhs = sparse_min[level - 1][i];
      const int& rhs = sparse_min[level - 1][i + half];
      sparse_min[level][i] = (lhs < rhs ? lhs : rhs);
    }
    EDULCNI_VIS(edulcni::live::matrix("sparse_table.table", sparse_min));
    EDULCNI_STEP("Sparse table built a level");
  }
  EDULCNI_STEP("Sparse table built");
}

int query_sparse_min(int left, int right) {
  const int n = sparse_min.empty() ? 0 : static_cast<int>(sparse_min[0].size());
  if (n == 0 || left > right || right < 0 || left >= n) {
    return int();
  }
  if (left < 0) {
    left = 0;
  }
  if (right >= n) {
    right = n - 1;
  }

  const int level = sparse_log[right - left + 1];
  const int& lhs = sparse_min[level][left];
  const int& rhs = sparse_min[level][right - (1 << level) + 1];
  const int result = lhs < rhs ? lhs : rhs;
  EDULCNI_VIS(edulcni::live::array("sparse_table.query", std::vector<int>{lhs, rhs, result}));
  EDULCNI_STEP("Sparse table answered a query");
  return result;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  std::vector<int> values = {5, 2, 7, 3, 9, 1, 4};
    build_sparse_min(values);
    assert(query_sparse_min(0, 6) == 1);
    assert(query_sparse_min(1, 3) == 2);
    std::cout << "minimum on [1, 3]: " << query_sparse_min(1, 3) << '\n';

  cout << "ok\n";
  return 0;
}
