// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/mo

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

struct MoQuery {
  int left;
  int right;  // [left, right)

  MoQuery(int left_ = 0, int right_ = 0) : left(left_), right(right_) {}
};

inline int mo_default_block_size(int n, int q) {
  const int safe_n = std::max(1, n);
  const int safe_q = std::max(1, q);
  const int block_from_n = static_cast<int>(std::sqrt(static_cast<double>(safe_n)));
  const int block_from_ratio =
      static_cast<int>(safe_n / std::max(1.0, std::sqrt(static_cast<double>(safe_q))));
  return std::max(1, std::max(block_from_n, block_from_ratio));
}

inline MoQuery normalize_mo_query(MoQuery query, int n) {
  query.left = std::max(0, std::min(query.left, n));
  query.right = std::max(0, std::min(query.right, n));
  if (query.left > query.right) {
    std::swap(query.left, query.right);
  }
  return query;
}

inline std::vector<int> mo_order(const std::vector<MoQuery>& queries, int n,
                                 int block_size = -1) {
  const int q = static_cast<int>(queries.size());
  if (block_size <= 0) {
    block_size = mo_default_block_size(n, q);
  }

  std::vector<MoQuery> normalized(q);
  for (int i = 0; i < q; ++i) {
    normalized[i] = normalize_mo_query(queries[i], n);
  }

  std::vector<int> order(q);
  std::iota(order.begin(), order.end(), 0);
  std::sort(order.begin(), order.end(), [&](int lhs_idx, int rhs_idx) {
    const MoQuery& lhs = normalized[lhs_idx];
    const MoQuery& rhs = normalized[rhs_idx];
    const int lhs_block = lhs.left / block_size;
    const int rhs_block = rhs.left / block_size;
    if (lhs_block != rhs_block) {
      return lhs_block < rhs_block;
    }
    if ((lhs_block & 1) == 0) {
      return lhs.right < rhs.right;
    }
    return lhs.right > rhs.right;
  });
  EDULCNI_VIS(edulcni::live::array("mo.order", order));
  EDULCNI_STEP("Mo queries ordered");
  return order;
}

template <typename AddLeft, typename AddRight, typename RemoveLeft, typename RemoveRight,
          typename GetAnswer>
inline std::vector<typename std::invoke_result<GetAnswer>::type> mo_process(
    int n, const std::vector<MoQuery>& queries, const AddLeft& add_left,
    const AddRight& add_right, const RemoveLeft& remove_left,
    const RemoveRight& remove_right, const GetAnswer& get_answer,
    int block_size = -1) {
  using Answer = typename std::invoke_result<GetAnswer>::type;
  const int q = static_cast<int>(queries.size());
  std::vector<Answer> answers(static_cast<std::size_t>(q));
  if (q == 0) {
    return answers;
  }

  std::vector<MoQuery> normalized(q);
  for (int i = 0; i < q; ++i) {
    normalized[i] = normalize_mo_query(queries[i], n);
  }

  const std::vector<int> order = mo_order(normalized, n, block_size);
  int cur_left = 0;
  int cur_right = 0;

  for (int index : order) {
    const MoQuery query = normalized[index];
    while (cur_left > query.left) {
      add_left(--cur_left);
    }
    while (cur_right < query.right) {
      add_right(cur_right++);
    }
    while (cur_left < query.left) {
      remove_left(cur_left++);
    }
    while (cur_right > query.right) {
      remove_right(--cur_right);
    }
    answers[index] = get_answer();
    EDULCNI_VIS(edulcni::live::array("mo.answers", answers));
    EDULCNI_VIS(edulcni::live::array(
        "mo.window", std::vector<int>{cur_left, cur_right}));
    EDULCNI_STEP("Mo algorithm answered a query");
  }
  return answers;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Answer offline range-distinct queries with Mo's ordering."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  const std::vector<int> values = {1, 2, 1, 3, 2, 4, 1};
    const std::vector<MoQuery> queries = {{0, 3}, {2, 7}, {0, 2}};
    std::vector<int> frequency(5, 0);
    int distinct = 0;
    auto add = [&](int index) { if (++frequency[values[index]] == 1) ++distinct; };
    auto remove = [&](int index) { if (--frequency[values[index]] == 0) --distinct; };
    auto answer = [&]() { return distinct; };
    const std::vector<int> result = mo_process(
        static_cast<int>(values.size()), queries, add, add, remove, remove, answer);
    assert((result == std::vector<int>{2, 4, 2}));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
