// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/ordered_set

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

#include <ext/pb_ds/assoc_container.hpp>
#include <ext/pb_ds/tree_policy.hpp>

template <typename Key, typename Compare = std::less<Key>>
using OrderedSetTree =
    __gnu_pbds::tree<Key, __gnu_pbds::null_type, Compare, __gnu_pbds::rb_tree_tag,
                     __gnu_pbds::tree_order_statistics_node_update>;

template <typename Key, typename Compare = std::less<Key>>
class OrderedSet {
 public:
  using key_type = Key;
  using tree_type = OrderedSetTree<Key, Compare>;
  using iterator = typename tree_type::iterator;
  using const_iterator = typename tree_type::const_iterator;

  bool insert(const Key& key) {
    const bool inserted = tree_.insert(key).second;
    trace(inserted ? "Ordered set inserted a key" : "Ordered set rejected a duplicate");
    return inserted;
  }

  bool erase(const Key& key) {
    const bool erased = tree_.erase(key) > 0;
    trace(erased ? "Ordered set erased a key" : "Ordered set did not find a key");
    return erased;
  }

  void clear() {
    tree_.clear();
    trace("Ordered set cleared");
  }

  int size() const { return static_cast<int>(tree_.size()); }

  bool empty() const { return tree_.empty(); }

  bool contains(const Key& key) const { return tree_.find(key) != tree_.end(); }

  int order_of_key(const Key& key) const {
    return static_cast<int>(tree_.order_of_key(key));
  }

  std::optional<Key> find_by_order(int order) const {
    if (order < 0 || order >= size()) {
      return std::nullopt;
    }
    const const_iterator it = tree_.find_by_order(order);
    if (it == tree_.end()) {
      return std::nullopt;
    }
    return *it;
  }

  iterator find(const Key& key) { return tree_.find(key); }

  const_iterator find(const Key& key) const { return tree_.find(key); }

  iterator lower_bound(const Key& key) { return tree_.lower_bound(key); }

  const_iterator lower_bound(const Key& key) const { return tree_.lower_bound(key); }

  iterator upper_bound(const Key& key) { return tree_.upper_bound(key); }

  const_iterator upper_bound(const Key& key) const { return tree_.upper_bound(key); }

  iterator begin() { return tree_.begin(); }

  const_iterator begin() const { return tree_.begin(); }

  iterator end() { return tree_.end(); }

  const_iterator end() const { return tree_.end(); }

  tree_type& raw() { return tree_; }

  const tree_type& raw() const { return tree_; }

 private:
  tree_type tree_;

  void trace(const char* label) const {
    EDULCNI_VIS(edulcni::live::array("ordered_set.values", tree_));
    EDULCNI_STEP(label);
  }
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Query ranks and k-th elements with a GNU PBDS ordered set."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  OrderedSet<int> ordered;
    assert(ordered.insert(8));
    assert(ordered.insert(3));
    assert(ordered.insert(10));
    assert(!ordered.insert(8));
    assert(ordered.order_of_key(9) == 2);
    assert(ordered.find_by_order(1).value() == 8);
    assert(ordered.erase(3));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
