import { cp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const thisFile = fileURLToPath(import.meta.url);
const thisDir = path.dirname(thisFile);
const extensionRoot = path.resolve(thisDir, "..");
const sourceRoot = path.resolve(extensionRoot, "..", "lib");
const targetRoot = path.resolve(extensionRoot, "library");
const manifestPath = path.join(extensionRoot, "package.json");
const generatedCommandsPath = path.join(extensionRoot, "src", "generatedCommands.ts");
const bundledEntries = ["templates", "catalog"];

function commandName(entry) {
  const name = path.posix.basename(entry.path);
  if (!/^[a-z0-9_]+$/.test(name)) {
    throw new Error(`catalog path cannot be exposed as a command: ${entry.path}`);
  }
  return name;
}

async function syncCommands() {
  const catalogPath = path.join(sourceRoot, "catalog", "snippets.json");
  const catalog = JSON.parse(await readFile(catalogPath, "utf8"));
  const commands = catalog.map((entry) => {
    const name = commandName(entry);
    return {
      command: `edulcni.${name}`,
      snippetPath: entry.path,
      title: `edulcni: ${name} — ${entry.insertMode === "global" ? "Global" : "Inline"}`
    };
  });
  const commandIds = commands.map(({ command }) => command);
  if (new Set(commandIds).size !== commandIds.length) {
    throw new Error("catalog paths produce duplicate command names");
  }

  const generatedSource = `// Generated by scripts/sync-library.mjs. Do not edit.\nexport const DIRECT_COMMANDS = ${JSON.stringify(
    commands.map(({ command, snippetPath }) => ({ command, snippetPath })),
    null,
    2
  )} as const;\n`;
  await writeFile(generatedCommandsPath, generatedSource);

  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  manifest.activationEvents = commandIds.map((command) => `onCommand:${command}`);
  manifest.contributes.commands = commands.map(({ command, title }) => ({ command, title }));
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
}

async function ensureSourceExists() {
  const sourceStat = await stat(sourceRoot);
  if (!sourceStat.isDirectory()) {
    throw new Error(`source is not a directory: ${sourceRoot}`);
  }
}

async function main() {
  await ensureSourceExists();
  await rm(targetRoot, { recursive: true, force: true });
  await mkdir(targetRoot, { recursive: true });
  for (const entry of bundledEntries) {
    await cp(path.join(sourceRoot, entry), path.join(targetRoot, entry), {
      recursive: true,
      force: true
    });
  }
  await syncCommands();
  console.log(`synced catalog snippets from ${sourceRoot} to ${targetRoot}`);
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`sync-library failed: ${message}`);
  process.exit(1);
});
