// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/lower_bound_flow

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <class Capacity>
class LowerBoundFlow {
 public:
  struct Edge { int from, to; Capacity lower, upper; };

  explicit LowerBoundFlow(int vertex_count)
      : vertex_count_(vertex_count), demands_(vertex_count, Capacity{}) {}

  void add_demand(int vertex, Capacity required_net_inflow) {
    demands_[vertex] += required_net_inflow;
  }

  int add_edge(int from, int to, Capacity lower, Capacity upper) {
    edges_.push_back({from, to, lower, upper});
    return static_cast<int>(edges_.size()) - 1;
  }

  bool feasible_circulation() {
    const int source = vertex_count_, sink = source + 1;
    graph_.assign(vertex_count_ + 2, {});
    positions_.clear();
    std::vector<Capacity> balance(vertex_count_);
    for (int vertex = 0; vertex < vertex_count_; ++vertex)
      balance[vertex] = -demands_[vertex];
    for (const Edge& edge : edges_) {
      if (edge.from < 0 || edge.from >= vertex_count_ || edge.to < 0 ||
          edge.to >= vertex_count_ || edge.lower < Capacity{} || edge.upper < edge.lower) {
        feasible_ = false;
        return false;
      }
      positions_.push_back(add_residual_edge(edge.from, edge.to, edge.upper - edge.lower));
      balance[edge.from] -= edge.lower;
      balance[edge.to] += edge.lower;
    }
    Capacity required{}, sink_capacity{};
    for (int vertex = 0; vertex < vertex_count_; ++vertex) {
      if (balance[vertex] > Capacity{}) {
        add_residual_edge(source, vertex, balance[vertex]);
        required += balance[vertex];
      } else if (balance[vertex] < Capacity{}) {
        add_residual_edge(vertex, sink, -balance[vertex]);
        sink_capacity += -balance[vertex];
      }
    }
    feasible_ = required == sink_capacity && max_flow(source, sink) == required;
    return feasible_;
  }

  std::vector<Capacity> edge_flows() const {
    assert(feasible_);
    std::vector<Capacity> result;
    result.reserve(edges_.size());
    for (int id = 0; id < static_cast<int>(edges_.size()); ++id) {
      auto [vertex, index] = positions_[id];
      const ResidualEdge& edge = graph_[vertex][index];
      result.push_back(edges_[id].upper - edge.capacity);
    }
    return result;
  }

 private:
  struct ResidualEdge { int to, reverse; Capacity capacity; };
  int vertex_count_;
  bool feasible_ = false;
  std::vector<Edge> edges_;
  std::vector<Capacity> demands_;
  std::vector<std::vector<ResidualEdge>> graph_;
  std::vector<std::pair<int, int>> positions_;

  std::pair<int, int> add_residual_edge(int from, int to, Capacity capacity) {
    int index = static_cast<int>(graph_[from].size());
    int reverse = static_cast<int>(graph_[to].size());
    graph_[from].push_back({to, reverse, capacity});
    graph_[to].push_back({from, index, Capacity{}});
    return {from, index};
  }

  Capacity max_flow(int source, int sink) {
    Capacity total{};
    std::vector<int> level(graph_.size()), next(graph_.size());
    while (true) {
      std::fill(level.begin(), level.end(), -1);
      std::vector<int> queue = {source}; level[source] = 0;
      for (int begin = 0; begin < static_cast<int>(queue.size()); ++begin) {
        int u = queue[begin];
        for (const auto& edge : graph_[u])
          if (edge.capacity > Capacity{} && level[edge.to] == -1) {
            level[edge.to] = level[u] + 1; queue.push_back(edge.to);
          }
      }
      if (level[sink] == -1) break;
      std::fill(next.begin(), next.end(), 0);
      std::function<Capacity(int, Capacity)> send = [&](int u, Capacity pushed) {
        if (u == sink) return pushed;
        for (int& i = next[u]; i < static_cast<int>(graph_[u].size()); ++i) {
          ResidualEdge& edge = graph_[u][i];
          if (edge.capacity <= Capacity{} || level[edge.to] != level[u] + 1) continue;
          Capacity sent = send(edge.to, std::min(pushed, edge.capacity));
          if (sent > Capacity{}) {
            edge.capacity -= sent;
            graph_[edge.to][edge.reverse].capacity += sent;
            return sent;
          }
        }
        return Capacity{};
      };
      while (Capacity pushed = send(source, std::numeric_limits<Capacity>::max())) total += pushed;
    }
    return total;
  }
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Find a feasible circulation with lower and upper edge bounds."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  LowerBoundFlow<long long> flow(3);
    flow.add_edge(0, 1, 2, 4);
    flow.add_edge(1, 2, 2, 4);
    flow.add_edge(2, 0, 2, 4);
    assert(flow.feasible_circulation());
    const auto edge_flows = flow.edge_flows();
    assert((edge_flows == std::vector<long long>{2, 2, 2}));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
