// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/berlekamp_massey

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename T>
inline std::vector<T> berlekamp_massey(const std::vector<T>& sequence) {
  const T zero = T(0);
  const T one = T(1);

  std::vector<T> current(1, one);
  std::vector<T> last(1, one);
  int order = 0;
  int shift = 1;
  T last_discrepancy = one;

  EDULCNI_VIS(edulcni::live::array("berlekamp_massey.sequence", sequence));
  EDULCNI_VIS(edulcni::live::array("berlekamp_massey.coefficients", current));
  EDULCNI_STEP("Berlekamp-Massey initialized");

  for (int i = 0; i < static_cast<int>(sequence.size()); ++i) {
    T discrepancy = sequence[i];
    for (int j = 1; j <= order; ++j) {
      discrepancy += current[j] * sequence[i - j];
    }

    if (discrepancy == zero) {
      ++shift;
      EDULCNI_VIS(edulcni::live::array("berlekamp_massey.coefficients", current));
      EDULCNI_STEP("Berlekamp-Massey accepted the current recurrence");
      continue;
    }

    const std::vector<T> previous = current;
    const T factor = discrepancy / last_discrepancy;
    if (static_cast<int>(current.size()) < static_cast<int>(last.size()) + shift) {
      current.resize(static_cast<int>(last.size()) + shift, zero);
    }
    for (int j = 0; j < static_cast<int>(last.size()); ++j) {
      current[j + shift] -= factor * last[j];
    }

    if (2 * order <= i) {
      order = i + 1 - order;
      last = previous;
      last_discrepancy = discrepancy;
      shift = 1;
    } else {
      ++shift;
    }
    EDULCNI_VIS(edulcni::live::array("berlekamp_massey.coefficients", current));
    EDULCNI_STEP("Berlekamp-Massey corrected the recurrence");
  }

  current.erase(current.begin());
  for (T& coefficient : current) {
    coefficient = zero - coefficient;
  }
  while (!current.empty() && current.back() == zero) {
    current.pop_back();
  }
  EDULCNI_VIS(edulcni::live::array("berlekamp_massey.coefficients", current));
  EDULCNI_STEP("Berlekamp-Massey completed");
  return current;
}


template <typename T>
inline T linear_recurrence_kth(const std::vector<T>& initial,
                               const std::vector<T>& coefficients,
                               long long index) {
  if (index < 0) {
    return T(0);
  }
  if (index < static_cast<long long>(initial.size())) {
    return initial[static_cast<int>(index)];
  }

  const int order = static_cast<int>(coefficients.size());
  if (order == 0) {
    return T(0);
  }

  auto combine = [&](const std::vector<T>& lhs, const std::vector<T>& rhs) {
    std::vector<T> result(2 * order, T(0));
    for (int i = 0; i < order; ++i) {
      for (int j = 0; j < order; ++j) {
        result[i + j] += lhs[i] * rhs[j];
      }
    }
    for (int i = 2 * order - 1; i >= order; --i) {
      for (int j = 0; j < order; ++j) {
        result[i - 1 - j] += result[i] * coefficients[j];
      }
    }
    result.resize(order);
    return result;
  };

  std::vector<T> seed(order, T(0));
  for (int i = 0; i < order && i < static_cast<int>(initial.size()); ++i) {
    seed[i] = initial[i];
  }

  std::vector<T> result(order, T(0));
  result[0] = T(1);

  std::vector<T> x(order, T(0));
  if (order == 1) {
    x[0] = coefficients[0];
  } else {
    x[1] = T(1);
  }

  long long power = index;
  EDULCNI_VIS(edulcni::live::array("linear_recurrence.initial", seed));
  EDULCNI_VIS(edulcni::live::array("linear_recurrence.coefficients", coefficients));
  EDULCNI_STEP("Linear recurrence exponentiation initialized");
  while (power > 0) {
    if (power & 1LL) {
      result = combine(result, x);
    }
    x = combine(x, x);
    power >>= 1LL;
    EDULCNI_VIS(edulcni::live::array("linear_recurrence.weights", result));
    EDULCNI_STEP("Linear recurrence consumed an exponent bit");
  }

  T answer = T(0);
  for (int i = 0; i < order; ++i) {
    answer += result[i] * seed[i];
  }
  return answer;
}


template <typename T>
inline T berlekamp_massey_kth(const std::vector<T>& sequence, long long index) {
  if (index < 0) {
    return T(0);
  }
  if (index < static_cast<long long>(sequence.size())) {
    return sequence[static_cast<int>(index)];
  }

  const std::vector<T> coefficients = berlekamp_massey(sequence);
  const int order = static_cast<int>(coefficients.size());
  if (order == 0) {
    return T(0);
  }

  std::vector<T> initial(order, T(0));
  for (int i = 0; i < order; ++i) {
    initial[i] = sequence[i];
  }
  return linear_recurrence_kth(initial, coefficients, index);
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Recover the Fibonacci recurrence and evaluate a later term."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  const std::vector<long double> sequence = {0, 1, 1, 2, 3, 5, 8, 13};
    const auto coefficients = berlekamp_massey(sequence);
    assert(coefficients.size() == 2);
    assert(std::abs(coefficients[0] - 1.0L) < 1e-12L);
    assert(std::abs(coefficients[1] - 1.0L) < 1e-12L);
    const long double term = linear_recurrence_kth(
        std::vector<long double>{0, 1}, coefficients, 10);
    assert(std::llround(term) == 55);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
