// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/dp_knapsack

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

inline long long knapsack_zero_one(const std::vector<int>& weight,
                                   const std::vector<long long>& value,
                                   int capacity) {
  std::vector<long long> dp(capacity + 1, 0);
  EDULCNI_VIS(edulcni::live::array("knapsack.weight", weight));
  EDULCNI_VIS(edulcni::live::array("knapsack.value", value));
  EDULCNI_VIS(edulcni::live::array("knapsack.dp", dp));
  EDULCNI_STEP("Zero-one knapsack initialized");
  for (int i = 0; i < static_cast<int>(weight.size()); ++i) {
    for (int sum = capacity; sum >= weight[i]; --sum) {
      const long long candidate = dp[sum - weight[i]] + value[i];
      if (candidate <= dp[sum]) continue;
      dp[sum] = candidate;
      EDULCNI_VIS(edulcni::live::array("knapsack.dp", dp));
      EDULCNI_VIS(edulcni::live::array_focus(
          "knapsack.weight", i, edulcni::live::FocusRole::active,
          "item considered"));
      EDULCNI_VIS(edulcni::live::array_focus(
          "knapsack.dp", std::vector<int>{sum - weight[i], sum},
          edulcni::live::FocusRole::changed,
          "transition improves this capacity"));
      EDULCNI_STEP("Zero-one knapsack improves a state");
    }
  }
  const int best = static_cast<int>(
      std::max_element(dp.begin(), dp.end()) - dp.begin());
  EDULCNI_VIS(edulcni::live::array_focus(
      "knapsack.dp", best, edulcni::live::FocusRole::result,
      "best achievable value"));
  EDULCNI_STEP("Zero-one knapsack completed");
  return dp[best];
}

inline long long knapsack_unbounded(const std::vector<int>& weight,
                                    const std::vector<long long>& value,
                                    int capacity) {
  std::vector<long long> dp(capacity + 1, 0);
  EDULCNI_VIS(edulcni::live::array("knapsack.weight", weight));
  EDULCNI_VIS(edulcni::live::array("knapsack.value", value));
  EDULCNI_VIS(edulcni::live::array("knapsack.dp", dp));
  EDULCNI_STEP("Unbounded knapsack initialized");
  for (int i = 0; i < static_cast<int>(weight.size()); ++i) {
    for (int sum = weight[i]; sum <= capacity; ++sum) {
      const long long candidate = dp[sum - weight[i]] + value[i];
      if (candidate <= dp[sum]) continue;
      dp[sum] = candidate;
      EDULCNI_VIS(edulcni::live::array("knapsack.dp", dp));
      EDULCNI_VIS(edulcni::live::array_focus(
          "knapsack.weight", i, edulcni::live::FocusRole::active,
          "item considered"));
      EDULCNI_VIS(edulcni::live::array_focus(
          "knapsack.dp", std::vector<int>{sum - weight[i], sum},
          edulcni::live::FocusRole::changed,
          "transition improves this capacity"));
      EDULCNI_STEP("Unbounded knapsack improves a state");
    }
  }
  const int best = static_cast<int>(
      std::max_element(dp.begin(), dp.end()) - dp.begin());
  EDULCNI_VIS(edulcni::live::array_focus(
      "knapsack.dp", best, edulcni::live::FocusRole::result,
      "best achievable value"));
  EDULCNI_STEP("Unbounded knapsack completed");
  return dp[best];
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Compare zero-one and unbounded one-dimensional knapsack."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  const std::vector<int> weights = {3, 4};
    const std::vector<long long> values = {5, 6};
    assert(knapsack_zero_one(weights, values, 6) == 6);
    assert(knapsack_unbounded(weights, values, 6) == 10);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
