// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/knuth_dp

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename Cost>
inline std::pair<std::vector<std::vector<long long>>, std::vector<std::vector<int>>>
knuth_interval_dp(int n, Cost cost) {
  std::vector<std::vector<long long>> dp(n + 1, std::vector<long long>(n + 1));
  std::vector<std::vector<int>> opt(n + 1, std::vector<int>(n + 1));
  for (int left = 0; left < n; ++left) opt[left][left + 1] = left + 1;
  EDULCNI_VIS(edulcni::live::matrix("knuth_dp.optimum", opt));
  EDULCNI_STEP("Knuth optimization initialized");
  for (int length = 2; length <= n; ++length) {
    for (int left = 0; left + length <= n; ++left) {
      const int right = left + length;
      dp[left][right] = std::numeric_limits<long long>::max();
      const int from = std::max(left + 1, opt[left][right - 1]);
      const int to = std::min(right - 1, opt[left + 1][right]);
      for (int split = from; split <= to; ++split) {
        const long long candidate = dp[left][split] + dp[split][right] + cost(left, right);
        if (candidate < dp[left][right]) {
          dp[left][right] = candidate;
          opt[left][right] = split;
        }
      }
    }
    EDULCNI_VIS(edulcni::live::matrix("knuth_dp.cost", dp));
    EDULCNI_VIS(edulcni::live::matrix("knuth_dp.optimum", opt));
    EDULCNI_VIS(edulcni::live::value("knuth_dp.length", length));
    EDULCNI_STEP("Knuth optimization completes an interval length");
  }
  return {dp, opt};
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Optimize adjacent interval merging with Knuth's bounds."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  const std::vector<long long> weights = {1, 2, 3, 4};
    std::vector<long long> prefix(weights.size() + 1);
    std::partial_sum(weights.begin(), weights.end(), prefix.begin() + 1);
    const auto [cost, optimum] = knuth_interval_dp(
        static_cast<int>(weights.size()),
        [&](int left, int right) { return prefix[right] - prefix[left]; });
    assert(cost[0][4] == 19);
    assert(0 < optimum[0][4] && optimum[0][4] < 4);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
