// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/sos_dp

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename T>
inline std::vector<T> subset_zeta_transform(std::vector<T> value, int bits) {
  EDULCNI_VIS(edulcni::live::array("sos.values", value));
  EDULCNI_STEP("Subset zeta transform initialized");
  for (int bit = 0; bit < bits; ++bit) {
    for (int mask = 0; mask < (1 << bits); ++mask)
      if (mask & (1 << bit)) value[mask] += value[mask ^ (1 << bit)];
    EDULCNI_VIS(edulcni::live::array("sos.values", value));
    EDULCNI_VIS(edulcni::live::bits(
        "sos.active_bit", static_cast<unsigned long long>(1) << bit, bits));
    EDULCNI_STEP("Subset zeta transform completes a bit");
  }
  return value;
}

template <typename T>
inline std::vector<T> subset_mobius_transform(std::vector<T> value, int bits) {
  EDULCNI_VIS(edulcni::live::array("sos.values", value));
  EDULCNI_STEP("Subset Mobius transform initialized");
  for (int bit = 0; bit < bits; ++bit) {
    for (int mask = 0; mask < (1 << bits); ++mask)
      if (mask & (1 << bit)) value[mask] -= value[mask ^ (1 << bit)];
    EDULCNI_VIS(edulcni::live::array("sos.values", value));
    EDULCNI_VIS(edulcni::live::bits(
        "sos.active_bit", static_cast<unsigned long long>(1) << bit, bits));
    EDULCNI_STEP("Subset Mobius transform completes a bit");
  }
  return value;
}

template <typename T>
inline std::vector<T> superset_zeta_transform(std::vector<T> value, int bits) {
  EDULCNI_VIS(edulcni::live::array("sos.values", value));
  EDULCNI_STEP("Superset zeta transform initialized");
  for (int bit = 0; bit < bits; ++bit) {
    for (int mask = 0; mask < (1 << bits); ++mask)
      if (!(mask & (1 << bit))) value[mask] += value[mask ^ (1 << bit)];
    EDULCNI_VIS(edulcni::live::array("sos.values", value));
    EDULCNI_VIS(edulcni::live::bits(
        "sos.active_bit", static_cast<unsigned long long>(1) << bit, bits));
    EDULCNI_STEP("Superset zeta transform completes a bit");
  }
  return value;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Apply subset zeta, Mobius, and superset zeta transforms."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  const std::vector<long long> values = {1, 2, 3, 4, 5, 6, 7, 8};
    const auto subset_sums = subset_zeta_transform(values, 3);
    assert((subset_sums == std::vector<long long>{1, 3, 4, 10, 6, 14, 16, 36}));
    assert(subset_mobius_transform(subset_sums, 3) == values);
    const auto superset_sums = superset_zeta_transform(values, 3);
    assert((superset_sums == std::vector<long long>{36, 20, 22, 12, 26, 14, 15, 8}));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
