// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/toposort

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

inline std::vector<int> topological_sort(const std::vector<std::vector<int>>& graph,
                                         bool* is_dag = nullptr) {
  const int n = static_cast<int>(graph.size());
  std::vector<int> indegree(n, 0);
  for (int v = 0; v < n; ++v) {
    for (int to : graph[v]) {
      if (to >= 0 && to < n) {
        ++indegree[to];
      }
    }
  }

  std::queue<int> q;
  for (int v = 0; v < n; ++v) {
    if (indegree[v] == 0) {
      q.push(v);
    }
  }

  std::vector<int> order;
  order.reserve(n);
  EDULCNI_VIS(edulcni::live::graph("toposort.graph", graph));
  EDULCNI_VIS(edulcni::live::array("toposort.indegree", indegree));
  EDULCNI_VIS(edulcni::live::queue("toposort.frontier", q));
  EDULCNI_STEP("Topological sort initialized");
  while (!q.empty()) {
    const int v = q.front();
    q.pop();
    order.push_back(v);
    for (int to : graph[v]) {
      if (to < 0 || to >= n) {
        continue;
      }
      --indegree[to];
      if (indegree[to] == 0) {
        q.push(to);
      }
    }
    EDULCNI_VIS(edulcni::live::array("toposort.indegree", indegree));
    EDULCNI_VIS(edulcni::live::array("toposort.order", order));
    EDULCNI_VIS(edulcni::live::queue("toposort.frontier", q));
    EDULCNI_STEP("Topological sort emitted a vertex");
  }

  const bool dag = static_cast<int>(order.size()) == n;
  if (is_dag != nullptr) {
    *is_dag = dag;
  }
  if (!dag) {
    EDULCNI_STEP("Topological sort found a cycle");
    return {};
  }
  EDULCNI_STEP("Topological sort completed");
  return order;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Topologically order a directed acyclic graph."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  std::vector<std::vector<int>> graph(6);
    graph[5].push_back(2);
    graph[5].push_back(0);
    graph[4].push_back(0);
    graph[4].push_back(1);
    graph[2].push_back(3);
    graph[3].push_back(1);
    bool is_dag = false;
    const std::vector<int> order = topological_sort(graph, &is_dag);
    assert(is_dag && order.size() == graph.size());

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
