// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/toposort

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

inline void toposort_add_edge(std::vector<std::vector<int>>& graph, int from, int to) {
  const int n = static_cast<int>(graph.size());
  if (from < 0 || from >= n || to < 0 || to >= n) {
    return;
  }
  graph[from].push_back(to);
  EDULCNI_VIS(edulcni::live::graph("toposort.graph", graph));
  EDULCNI_STEP("Topological-sort edge added");
}

inline std::vector<int> topological_sort(const std::vector<std::vector<int>>& graph,
                                         bool* is_dag = nullptr) {
  const int n = static_cast<int>(graph.size());
  std::vector<int> indegree(n, 0);
  for (int v = 0; v < n; ++v) {
    for (int to : graph[v]) {
      if (to >= 0 && to < n) {
        ++indegree[to];
      }
    }
  }

  std::queue<int> q;
  for (int v = 0; v < n; ++v) {
    if (indegree[v] == 0) {
      q.push(v);
    }
  }

  std::vector<int> order;
  order.reserve(n);
  EDULCNI_VIS(edulcni::live::graph("toposort.graph", graph));
  EDULCNI_VIS(edulcni::live::array("toposort.indegree", indegree));
  EDULCNI_VIS(edulcni::live::queue("toposort.frontier", q));
  EDULCNI_STEP("Topological sort initialized");
  while (!q.empty()) {
    const int v = q.front();
    q.pop();
    order.push_back(v);
    for (int to : graph[v]) {
      if (to < 0 || to >= n) {
        continue;
      }
      --indegree[to];
      if (indegree[to] == 0) {
        q.push(to);
      }
    }
    EDULCNI_VIS(edulcni::live::array("toposort.indegree", indegree));
    EDULCNI_VIS(edulcni::live::array("toposort.order", order));
    EDULCNI_VIS(edulcni::live::queue("toposort.frontier", q));
    EDULCNI_STEP("Topological sort emitted a vertex");
  }

  const bool dag = static_cast<int>(order.size()) == n;
  if (is_dag != nullptr) {
    *is_dag = dag;
  }
  if (!dag) {
    EDULCNI_STEP("Topological sort found a cycle");
    return {};
  }
  EDULCNI_STEP("Topological sort completed");
  return order;
}

inline bool is_topological_order(const std::vector<std::vector<int>>& graph,
                                 const std::vector<int>& order) {
  const int n = static_cast<int>(graph.size());
  if (static_cast<int>(order.size()) != n) {
    return false;
  }

  std::vector<int> position(n, -1);
  for (int i = 0; i < n; ++i) {
    const int v = order[i];
    if (v < 0 || v >= n || position[v] != -1) {
      return false;
    }
    position[v] = i;
  }

  for (int v = 0; v < n; ++v) {
    for (int to : graph[v]) {
      if (to < 0 || to >= n) {
        continue;
      }
      if (position[v] > position[to]) {
        return false;
      }
    }
  }
  return true;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Topologically order a directed acyclic graph."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  std::vector<std::vector<int>> graph(6);
    toposort_add_edge(graph, 5, 2);
    toposort_add_edge(graph, 5, 0);
    toposort_add_edge(graph, 4, 0);
    toposort_add_edge(graph, 4, 1);
    toposort_add_edge(graph, 2, 3);
    toposort_add_edge(graph, 3, 1);
    bool is_dag = false;
    const std::vector<int> order = topological_sort(graph, &is_dag);
    assert(is_dag && is_topological_order(graph, order));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
