// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/aliens_trick

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

struct AliensTrickResult {
  long long objective;
  long long lambda;
  int selected_count;
};

template <typename SolvePenalized>
inline AliensTrickResult aliens_trick_min_exact(
    int target_count, long long min_lambda, long long max_lambda,
    SolvePenalized solve_penalized) {
  long long left = min_lambda, right = max_lambda;
  while (left < right) {
    const long long middle = left + (right - left + 1) / 2;
    const auto [penalized_value, count] = solve_penalized(middle);
    EDULCNI_VIS(edulcni::live::array(
        "aliens_trick.lambda_bounds", std::vector<long long>{left, middle, right}));
    EDULCNI_VIS(edulcni::live::value("aliens_trick.penalized_value", penalized_value));
    EDULCNI_VIS(edulcni::live::value("aliens_trick.selected_count", count));
    EDULCNI_STEP("Aliens trick evaluates a penalty");
    if (count >= target_count) left = middle;
    else right = middle - 1;
  }
  const auto [penalized_value, count] = solve_penalized(left);
  const AliensTrickResult result{
      penalized_value - left * target_count, left, count};
  EDULCNI_VIS(edulcni::live::value("aliens_trick.objective", result.objective));
  EDULCNI_VIS(edulcni::live::value("aliens_trick.lambda", result.lambda));
  EDULCNI_VIS(edulcni::live::value("aliens_trick.selected_count", result.selected_count));
  EDULCNI_STEP("Aliens trick completed");
  return result;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Recover the optimum for an exact count through lambda search."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  const std::array<long long, 5> objective = {16, 9, 4, 1, 0};
    const auto solve_penalized = [&](long long lambda) {
      std::pair<long long, int> best = {
          std::numeric_limits<long long>::max(), -1};
      for (int count = 0; count < static_cast<int>(objective.size()); ++count) {
        const long long candidate = objective[count] + lambda * count;
        if (candidate <= best.first) best = {candidate, count};
      }
      return best;
    };
    const auto result = aliens_trick_min_exact(2, -10, 10, solve_penalized);
    assert(result.objective == 4);
    assert(result.lambda == 5);
    assert(result.selected_count == 2);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
