// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/tree_hash

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

struct TreeHasher {
  std::map<std::vector<int>, int> ids;

  int rooted_hash(const std::vector<std::vector<int>>& graph, int root) {
    EDULCNI_VIS(edulcni::live::graph("tree_hash.tree", graph));
    EDULCNI_VIS(edulcni::live::value("tree_hash.root", root));
    EDULCNI_STEP("Rooted tree hashing initialized");
    return rooted_hash_dfs(graph, root, -1);
  }

  std::pair<int, int> hash(const std::vector<std::vector<int>>& graph) {
    if (graph.empty()) return {0, 0};
    auto centers = tree_centers(graph);
    int first = rooted_hash(graph, centers[0]);
    int second = centers.size() == 1 ? first : rooted_hash(graph, centers[1]);
    if (first > second) std::swap(first, second);
    return {first, second};
  }

 private:
  int rooted_hash_dfs(const std::vector<std::vector<int>>& graph, int node, int parent) {
    std::vector<int> children;
    for (int next : graph[node]) {
      if (next != parent) children.push_back(rooted_hash_dfs(graph, next, node));
    }
    std::sort(children.begin(), children.end());
    auto [it, inserted] = ids.emplace(children, int(ids.size()) + 1);
    EDULCNI_VIS(edulcni::live::array("tree_hash.children", children));
    EDULCNI_VIS(edulcni::live::value("tree_hash.node", node));
    EDULCNI_VIS(edulcni::live::value("tree_hash.value", it->second));
    EDULCNI_STEP("Tree node hash computed");
    return it->second;
  }

  static std::vector<int> tree_centers(const std::vector<std::vector<int>>& graph) {
    int n = graph.size();
    if (n <= 2) {
      std::vector<int> centers(n);
      std::iota(centers.begin(), centers.end(), 0);
      return centers;
    }
    std::vector<int> degree(n);
    std::queue<int> leaves;
    for (int node = 0; node < n; ++node) {
      degree[node] = graph[node].size();
      if (degree[node] <= 1) leaves.push(node);
    }
    EDULCNI_VIS(edulcni::live::array("tree_hash.degree", degree));
    EDULCNI_VIS(edulcni::live::queue("tree_hash.leaves", leaves));
    EDULCNI_STEP("Tree center peeling initialized");
    int remaining = n;
    while (remaining > 2) {
      int layer_size = leaves.size();
      remaining -= layer_size;
      while (layer_size--) {
        int node = leaves.front();
        leaves.pop();
        for (int next : graph[node]) {
          if (--degree[next] == 1) leaves.push(next);
        }
      }
      EDULCNI_VIS(edulcni::live::array("tree_hash.degree", degree));
      EDULCNI_VIS(edulcni::live::queue("tree_hash.leaves", leaves));
      EDULCNI_STEP("Tree center layer removed");
    }
    std::vector<int> centers;
    while (!leaves.empty()) {
      centers.push_back(leaves.front());
      leaves.pop();
    }
    return centers;
  }
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  std::vector<std::vector<int>> first(6), second(6);
    const auto add_edge = [](std::vector<std::vector<int>>& graph, int u, int v) {
      graph[u].push_back(v);
      graph[v].push_back(u);
    };
    add_edge(first, 0, 1);
    add_edge(first, 1, 2);
    add_edge(first, 1, 3);
    add_edge(first, 3, 4);
    add_edge(first, 3, 5);

    add_edge(second, 5, 4);
    add_edge(second, 4, 3);
    add_edge(second, 4, 2);
    add_edge(second, 2, 1);
    add_edge(second, 2, 0);

    TreeHasher hasher;
    assert(hasher.hash(first) == hasher.hash(second));

  cout << "ok\n";
  return 0;
}
