// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/dijkstra

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename Weight>
struct DijkstraEdge {
  int to;
  Weight weight;

  DijkstraEdge(int to_ = 0, const Weight& weight_ = Weight())
      : to(to_), weight(weight_) {}

  friend std::istream& operator>>(std::istream& in, DijkstraEdge& edge) {
    return in >> edge.to >> edge.weight;
  }

  friend std::ostream& operator<<(std::ostream& out, const DijkstraEdge& edge) {
    return out << edge.to << ' ' << edge.weight;
  }
};

template <typename Weight>
struct DijkstraResult {
  std::vector<Weight> distance;
  std::vector<int> parent;
};

template <typename Weight, typename WeightArg>
void dijkstra_add_edge(std::vector<std::vector<DijkstraEdge<Weight>>>& graph,
                       int from, int to, const WeightArg& weight,
                       bool undirected = false) {
  const int n = static_cast<int>(graph.size());
  if (from < 0 || from >= n || to < 0 || to >= n) {
    return;
  }
  graph[from].push_back(DijkstraEdge<Weight>(to, static_cast<Weight>(weight)));
  if (undirected && from != to) {
    graph[to].push_back(DijkstraEdge<Weight>(from, static_cast<Weight>(weight)));
  }
  EDULCNI_VIS(edulcni::live::weighted_graph("dijkstra.graph", graph));
  EDULCNI_STEP("Dijkstra edge added");
}

template <typename Weight>
DijkstraResult<Weight> dijkstra_multi_source(
    const std::vector<std::vector<DijkstraEdge<Weight>>>& graph,
    const std::vector<int>& sources,
    Weight inf = std::numeric_limits<Weight>::max()) {
  const int n = static_cast<int>(graph.size());
  DijkstraResult<Weight> result;
  result.distance.assign(n, inf);
  result.parent.assign(n, -1);

  using Node = std::pair<Weight, int>;
  std::priority_queue<Node, std::vector<Node>, std::greater<Node>> pq;

  for (int source : sources) {
    if (source < 0 || source >= n || result.distance[source] == Weight(0)) {
      continue;
    }
    result.distance[source] = Weight(0);
    pq.push(Node(Weight(0), source));
  }

  EDULCNI_VIS(edulcni::live::weighted_graph("dijkstra.graph", graph));
  EDULCNI_VIS(edulcni::live::array("dijkstra.distance", result.distance));
  EDULCNI_VIS(edulcni::live::priority_queue("dijkstra.frontier", pq));
  EDULCNI_STEP("Dijkstra initialized");

  while (!pq.empty()) {
    const Weight dist = pq.top().first;
    const int v = pq.top().second;
    pq.pop();

    if (dist != result.distance[v]) {
      continue;
    }
    for (const DijkstraEdge<Weight>& edge : graph[v]) {
      if (edge.to < 0 || edge.to >= n || edge.weight < Weight(0)) {
        continue;
      }
      const Weight candidate = dist + edge.weight;
      if (candidate < result.distance[edge.to]) {
        result.distance[edge.to] = candidate;
        result.parent[edge.to] = v;
        pq.push(Node(candidate, edge.to));
        EDULCNI_VIS(edulcni::live::array("dijkstra.distance", result.distance));
        EDULCNI_VIS(edulcni::live::array("dijkstra.parent", result.parent));
        EDULCNI_VIS(edulcni::live::priority_queue("dijkstra.frontier", pq));
        EDULCNI_VIS(edulcni::live::graph_focus(
            "dijkstra.graph", std::vector<int>{v, edge.to},
            std::vector<std::pair<int, int>>{std::make_pair(v, edge.to)},
            edulcni::live::FocusRole::accepted,
            "edge improves the shortest known distance"));
        EDULCNI_VIS(edulcni::live::array_focus(
            "dijkstra.distance", edge.to,
            edulcni::live::FocusRole::changed, "distance decreased"));
        EDULCNI_VIS(edulcni::live::array_focus(
            "dijkstra.parent", edge.to,
            edulcni::live::FocusRole::changed, "predecessor changed"));
        EDULCNI_STEP("Dijkstra relaxed an edge");
      }
    }
  }

  EDULCNI_STEP("Dijkstra completed");

  return result;
}

template <typename Weight>
DijkstraResult<Weight> dijkstra(
    const std::vector<std::vector<DijkstraEdge<Weight>>>& graph, int source,
    Weight inf = std::numeric_limits<Weight>::max()) {
  return dijkstra_multi_source(graph, std::vector<int>(1, source), inf);
}

template <typename Weight>
std::vector<int> dijkstra_restore_path(int source, int target,
                                       const DijkstraResult<Weight>& result) {
  const int n = static_cast<int>(result.parent.size());
  if (source < 0 || source >= n || target < 0 || target >= n) {
    return {};
  }

  std::vector<int> path;
  int current = target;
  int steps = 0;
  while (current != -1 && steps <= n) {
    path.push_back(current);
    current = result.parent[current];
    ++steps;
  }

  if (path.empty() || path.back() != source) {
    return {};
  }
  std::reverse(path.begin(), path.end());
  EDULCNI_VIS(edulcni::live::array("dijkstra.path", path));
  EDULCNI_VIS(edulcni::live::graph_path_focus(
      "dijkstra.graph", path, edulcni::live::FocusRole::result,
      "restored shortest path"));
  EDULCNI_STEP("Dijkstra restored a path");
  return path;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Trace shortest paths in a small weighted graph."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  const long long infinity = std::numeric_limits<long long>::max();
    std::vector<std::vector<DijkstraEdge<long long>>> graph(5);
    dijkstra_add_edge(graph, 0, 1, 10);
    dijkstra_add_edge(graph, 0, 2, 3);
    dijkstra_add_edge(graph, 2, 1, 1);
    dijkstra_add_edge(graph, 1, 3, 2);
    dijkstra_add_edge(graph, 2, 3, 8);
    dijkstra_add_edge(graph, 3, 4, 2);
    const DijkstraResult<long long> result = dijkstra(graph, 0, infinity);
    assert(result.distance[4] == 8);
    assert((dijkstra_restore_path(0, 4, result) == std::vector<int>{0, 2, 1, 3, 4}));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
