// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/hld

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

class HeavyLightDecomposition {
 public:
  explicit HeavyLightDecomposition(int n = 0) : n_(0), root_(0), timer_(0) {
    reset(n);
  }

  void reset(int n) {
    n_ = (n < 0 ? 0 : n);
    root_ = 0;
    timer_ = 0;
    graph_.assign(n_, std::vector<int>());
    parent_.assign(n_, -1);
    depth_.assign(n_, 0);
    subtree_size_.assign(n_, 0);
    heavy_.assign(n_, -1);
    head_.assign(n_, 0);
    pos_.assign(n_, -1);
    order_.assign(n_, -1);
    trace("Heavy-light decomposition reset");
  }

  int size() const { return n_; }

  void add_edge(int u, int v, bool undirected = true) {
    if (u < 0 || u >= n_ || v < 0 || v >= n_) {
      return;
    }
    graph_[u].push_back(v);
    if (undirected && u != v) {
      graph_[v].push_back(u);
    }
    trace("Heavy-light decomposition edge added");
  }

  void build(int root = 0) {
    if (n_ == 0) {
      return;
    }
    if (root < 0 || root >= n_) {
      root = 0;
    }
    root_ = root;

    std::fill(parent_.begin(), parent_.end(), -1);
    std::fill(depth_.begin(), depth_.end(), 0);
    std::fill(subtree_size_.begin(), subtree_size_.end(), 0);
    std::fill(heavy_.begin(), heavy_.end(), -1);
    std::fill(head_.begin(), head_.end(), 0);
    std::fill(pos_.begin(), pos_.end(), -1);
    std::fill(order_.begin(), order_.end(), -1);

    dfs_size(root_, -1);
    timer_ = 0;
    dfs_decompose(root_, root_);
    trace("Heavy-light decomposition built");
  }

  int root() const { return root_; }

  const std::vector<std::vector<int>>& graph() const { return graph_; }

  int parent(int v) const { return vertex_ok(v) ? parent_[v] : -1; }

  int depth(int v) const { return vertex_ok(v) ? depth_[v] : -1; }

  int heavy_child(int v) const { return vertex_ok(v) ? heavy_[v] : -1; }

  int head(int v) const { return vertex_ok(v) ? head_[v] : -1; }

  int position(int v) const { return vertex_ok(v) ? pos_[v] : -1; }

  int vertex_at(int pos) const {
    if (pos < 0 || pos >= n_) {
      return -1;
    }
    return order_[pos];
  }







 private:
  int n_;
  int root_;
  int timer_;
  std::vector<std::vector<int>> graph_;
  std::vector<int> parent_;
  std::vector<int> depth_;
  std::vector<int> subtree_size_;
  std::vector<int> heavy_;
  std::vector<int> head_;
  std::vector<int> pos_;
  std::vector<int> order_;

  void trace(const char* label) const {
    EDULCNI_VIS(edulcni::live::graph("hld.tree", graph_));
    EDULCNI_VIS(edulcni::live::array("hld.parent", parent_));
    EDULCNI_VIS(edulcni::live::array("hld.heavy", heavy_));
    EDULCNI_VIS(edulcni::live::array("hld.head", head_));
    EDULCNI_VIS(edulcni::live::array("hld.position", pos_));
    EDULCNI_STEP(label);
  }

  bool vertex_ok(int v) const { return v >= 0 && v < n_; }

  int dfs_size(int v, int parent) {
    parent_[v] = parent;
    subtree_size_[v] = 1;
    int best_size = 0;
    int best_child = -1;

    for (int to : graph_[v]) {
      if (to == parent) {
        continue;
      }
      depth_[to] = depth_[v] + 1;
      const int child_size = dfs_size(to, v);
      subtree_size_[v] += child_size;
      if (child_size > best_size) {
        best_size = child_size;
        best_child = to;
      }
    }
    heavy_[v] = best_child;
    return subtree_size_[v];
  }

  void dfs_decompose(int v, int head) {
    head_[v] = head;
    pos_[v] = timer_;
    order_[timer_] = v;
    ++timer_;

    if (heavy_[v] != -1) {
      dfs_decompose(heavy_[v], head);
    }
    for (int to : graph_[v]) {
      if (to == parent_[v] || to == heavy_[v]) {
        continue;
      }
      dfs_decompose(to, to);
    }
  }
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Decompose tree paths into contiguous heavy-light segments."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  HeavyLightDecomposition hld(7);
    hld.add_edge(0, 1);
    hld.add_edge(0, 2);
    hld.add_edge(1, 3);
    hld.add_edge(1, 4);
    hld.add_edge(2, 5);
    hld.add_edge(2, 6);
    hld.build(0);
    assert(hld.lca(3, 4) == 1);
    assert(hld.lca(3, 6) == 0);
    const auto subtree = hld.subtree_segment(2);
    assert(subtree.second - subtree.first + 1 == 3);
    const auto path = hld.path_segments(3, 6, true);
    assert(!path.empty());

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
