// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/kosaraju

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

struct KosarajuResult {
  int component_count;
  std::vector<int> component_of;
  std::vector<std::vector<int>> components;

};



inline KosarajuResult kosaraju_scc(const std::vector<std::vector<int>>& graph) {
  const int n = static_cast<int>(graph.size());
  std::vector<std::vector<int>> reverse_graph(n);
  for (int v = 0; v < n; ++v) {
    for (int to : graph[v]) {
      if (to >= 0 && to < n) {
        reverse_graph[to].push_back(v);
      }
    }
  }

  std::vector<char> used(n, 0);
  std::vector<int> order;
  order.reserve(n);
  EDULCNI_VIS(edulcni::live::graph("kosaraju.graph", graph));
  EDULCNI_STEP("Kosaraju initialized");

  std::function<void(int)> dfs1 = [&](int v) {
    used[v] = 1;
    for (int to : graph[v]) {
      if (to < 0 || to >= n || used[to]) {
        continue;
      }
      dfs1(to);
    }
    order.push_back(v);
  };

  for (int v = 0; v < n; ++v) {
    if (!used[v]) {
      dfs1(v);
    }
  }
  EDULCNI_VIS(edulcni::live::array("kosaraju.finish_order", order));
  EDULCNI_STEP("Kosaraju completed the first pass");

  KosarajuResult result;
  result.component_of.assign(n, -1);
  result.component_count = 0;

  std::function<void(int, int)> dfs2 = [&](int v, int comp) {
    result.component_of[v] = comp;
    result.components[comp].push_back(v);
    for (int to : reverse_graph[v]) {
      if (result.component_of[to] == -1) {
        dfs2(to, comp);
      }
    }
  };

  for (int i = n - 1; i >= 0; --i) {
    const int v = order[i];
    if (result.component_of[v] != -1) {
      continue;
    }
    result.components.push_back(std::vector<int>());
    dfs2(v, result.component_count);
    ++result.component_count;
    EDULCNI_VIS(edulcni::live::array("kosaraju.component", result.component_of));
    EDULCNI_STEP("Kosaraju discovered a component");
  }



  return result;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Find strongly connected components and their condensation graph."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  std::vector<std::vector<int>> graph(6);
    kosaraju_add_edge(graph, 0, 1);
    kosaraju_add_edge(graph, 1, 2);
    kosaraju_add_edge(graph, 2, 0);
    kosaraju_add_edge(graph, 2, 3);
    kosaraju_add_edge(graph, 3, 4);
    kosaraju_add_edge(graph, 4, 3);
    kosaraju_add_edge(graph, 4, 5);
    const KosarajuResult result = kosaraju_scc(graph);
    assert(result.component_count == 3);
    assert(result.component_of[0] == result.component_of[2]);
    assert(result.component_of[3] == result.component_of[4]);
    assert(result.component_of[4] != result.component_of[5]);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
