// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/gp_hash_table

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

#include <ext/pb_ds/assoc_container.hpp>

struct SplitMix64Hash {
  static std::uint64_t mix(std::uint64_t x) {
    x += 0x9e3779b97f4a7c15ULL;
    x = (x ^ (x >> 30)) * 0xbf58476d1ce4e5b9ULL;
    x = (x ^ (x >> 27)) * 0x94d049bb133111ebULL;
    x ^= (x >> 31);
    return x;
  }

  std::size_t operator()(std::uint64_t x) const {
    return static_cast<std::size_t>(mix(x));
  }
};

template <typename Key>
struct GpHash {
  std::size_t operator()(const Key& key) const {
    const std::uint64_t base = static_cast<std::uint64_t>(std::hash<Key>()(key));
    return static_cast<std::size_t>(SplitMix64Hash::mix(base));
  }
};

template <typename First, typename Second, typename FirstHash = GpHash<First>,
          typename SecondHash = GpHash<Second>>
struct PairHash {
  std::size_t operator()(const std::pair<First, Second>& value) const {
    const std::uint64_t h1 = static_cast<std::uint64_t>(FirstHash()(value.first));
    const std::uint64_t h2 = static_cast<std::uint64_t>(SecondHash()(value.second));
    return static_cast<std::size_t>(
        SplitMix64Hash::mix(h1 ^ (h2 + 0x9e3779b97f4a7c15ULL + (h1 << 6) + (h1 >> 2))));
  }
};

template <typename Key, typename Value, typename Hash = GpHash<Key>>
using GpHashTable = __gnu_pbds::gp_hash_table<Key, Value, Hash>;

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Use hardened hashes with GNU PBDS hash tables."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  GpHashTable<long long, int> table;
    table[5] = 11;
    table[5] += 4;
    table[8] = 3;
    assert(table[5] == 15);
    assert(table.find(8) != table.end());

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
