// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/dsu

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

class Dsu {
 public:
  explicit Dsu(int n = 0) { reset(n); }

  void reset(int n) {
    n_ = (n < 0 ? 0 : n);
    components_ = n_;
    parent_.resize(n_);
    size_.assign(n_, 1);
    for (int i = 0; i < n_; ++i) {
      parent_[i] = i;
    }
    EDULCNI_VIS(edulcni::live::forest("dsu.forest", parent_));
    EDULCNI_VIS(edulcni::live::array("dsu.size", size_));
    EDULCNI_VIS(edulcni::label_widget("dsu.components", components_));
    EDULCNI_STEP("DSU initialized");
  }

  int size() const { return n_; }

  int components() const { return components_; }

  int find(int v) {
    if (v < 0 || v >= n_) {
      return -1;
    }
    if (parent_[v] == v) {
      return v;
    }
    parent_[v] = find(parent_[v]);
    return parent_[v];
  }

  bool unite(int a, int b) {
    int root_a = find(a);
    int root_b = find(b);
    if (root_a == -1 || root_b == -1 || root_a == root_b) {
      return false;
    }

    if (size_[root_a] > size_[root_b]) {
      std::swap(root_a, root_b);
    }
    parent_[root_a] = root_b;
    size_[root_b] += size_[root_a];
    --components_;
    EDULCNI_VIS(edulcni::live::forest("dsu.forest", parent_));
    EDULCNI_VIS(edulcni::live::array("dsu.size", size_));
    EDULCNI_VIS(edulcni::label_widget("dsu.components", components_));
    EDULCNI_VIS(edulcni::live::graph_focus(
        "dsu.forest", std::vector<int>{root_a, root_b},
        std::vector<std::pair<int, int>>{
            std::make_pair(root_a, root_b)},
        edulcni::live::FocusRole::changed,
        "smaller component attached to larger root"));
    EDULCNI_VIS(edulcni::live::array_focus(
        "dsu.size", root_b, edulcni::live::FocusRole::changed,
        "component size increased"));
    EDULCNI_STEP("DSU merges two components");
    return true;
  }

  bool same(int a, int b) { return find(a) == find(b) && find(a) != -1; }

  int component_size(int v) {
    const int root = find(v);
    if (root == -1) {
      return 0;
    }
    return size_[root];
  }

  const std::vector<int>& parents() const { return parent_; }

 private:
  int n_;
  int components_;
  std::vector<int> parent_;
  std::vector<int> size_;
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Merge components and inspect the resulting parent forest."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  Dsu dsu(6);
    assert(dsu.unite(0, 1));
    assert(dsu.unite(1, 2));
    assert(dsu.unite(4, 5));
    assert(dsu.same(0, 2));
    assert(!dsu.same(2, 4));
    assert(dsu.component_size(1) == 3);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
