// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/segtree_beats

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename T>
class SegmentTreeBeats {
 public:
  explicit SegmentTreeBeats(int n = 0) { reset(n); }

  explicit SegmentTreeBeats(const std::vector<T>& values) { build(values); }

  void reset(int n) {
    n_ = n < 0 ? 0 : n;
    tree_.assign(4 * std::max(1, n_), empty_node());
    trace("Segment-tree beats reset");
  }

  void build(const std::vector<T>& values) {
    reset(static_cast<int>(values.size()));
    if (n_ > 0) {
      build_rec(1, 0, n_ - 1, values);
    }
    EDULCNI_VIS(edulcni::live::array("segment_tree_beats.values", values));
    trace("Segment-tree beats built");
  }

  int size() const { return n_; }


  void chmin(int left, int right, const T& x) {
    if (norm(left, right)) {
      chmin_rec(1, 0, n_ - 1, left, right, x);
      trace("Segment-tree beats applied chmin");
    }
  }



  void chmax(int left, int right, const T& x) {
    if (norm(left, right)) {
      chmax_rec(1, 0, n_ - 1, left, right, x);
      trace("Segment-tree beats applied chmax");
    }
  }



  void add(int left, int right, const T& x) {
    if (norm(left, right)) {
      add_rec(1, 0, n_ - 1, left, right, x);
      trace("Segment-tree beats added over a range");
    }
  }



  T query_sum(int left, int right) {
    if (!norm(left, right)) {
      return T(0);
    }
    return query_sum_rec(1, 0, n_ - 1, left, right);
  }



  T query_min(int left, int right) {
    if (!norm(left, right)) {
      return pos_inf();
    }
    return query_min_rec(1, 0, n_ - 1, left, right);
  }



  T query_max(int left, int right) {
    if (!norm(left, right)) {
      return neg_inf();
    }
    return query_max_rec(1, 0, n_ - 1, left, right);
  }


 private:
  struct Node {
    T sum;
    T max_v;
    T smax_v;
    int max_count;
    T min_v;
    T smin_v;
    int min_count;
    T add;
  };

  int n_;
  std::vector<Node> tree_;

  void trace(const char* label) const {
    EDULCNI_VIS(edulcni::live::segment_tree(
        "segment_tree_beats.tree", static_cast<std::size_t>(n_), tree_));
    EDULCNI_STEP(label);
  }

  static T pos_inf() { return std::numeric_limits<T>::max() / T(4); }
  static T neg_inf() { return std::numeric_limits<T>::lowest() / T(4); }

  static Node empty_node() {
    return {T(0), neg_inf(), neg_inf(), 0, pos_inf(), pos_inf(), 0, T(0)};
  }

  static Node make_leaf(const T& value) {
    return {value, value, neg_inf(), 1, value, pos_inf(), 1, T(0)};
  }

  static bool empty(const Node& node) { return node.max_count == 0; }

  bool norm(int& left, int& right) const {
    if (n_ == 0 || left > right || right < 0 || left >= n_) {
      return false;
    }
    left = std::max(left, 0);
    right = std::min(right, n_ - 1);
    return left <= right;
  }

  static Node merge_node(const Node& a, const Node& b) {
    if (empty(a)) {
      return b;
    }
    if (empty(b)) {
      return a;
    }

    Node res;
    res.sum = a.sum + b.sum;
    res.add = T(0);

    if (a.max_v == b.max_v) {
      res.max_v = a.max_v;
      res.max_count = a.max_count + b.max_count;
      res.smax_v = std::max(a.smax_v, b.smax_v);
    } else if (a.max_v > b.max_v) {
      res.max_v = a.max_v;
      res.max_count = a.max_count;
      res.smax_v = std::max(a.smax_v, b.max_v);
    } else {
      res.max_v = b.max_v;
      res.max_count = b.max_count;
      res.smax_v = std::max(a.max_v, b.smax_v);
    }

    if (a.min_v == b.min_v) {
      res.min_v = a.min_v;
      res.min_count = a.min_count + b.min_count;
      res.smin_v = std::min(a.smin_v, b.smin_v);
    } else if (a.min_v < b.min_v) {
      res.min_v = a.min_v;
      res.min_count = a.min_count;
      res.smin_v = std::min(a.smin_v, b.min_v);
    } else {
      res.min_v = b.min_v;
      res.min_count = b.min_count;
      res.smin_v = std::min(a.min_v, b.smin_v);
    }

    return res;
  }

  void build_rec(int v, int tl, int tr, const std::vector<T>& values) {
    if (tl == tr) {
      tree_[v] = make_leaf(values[tl]);
      return;
    }
    const int tm = (tl + tr) / 2;
    build_rec(v * 2, tl, tm, values);
    build_rec(v * 2 + 1, tm + 1, tr, values);
    pull(v);
  }

  void pull(int v) { tree_[v] = merge_node(tree_[v * 2], tree_[v * 2 + 1]); }


  void apply_add(int v, int tl, int tr, const T& x) {
    Node& node = tree_[v];
    node.sum += x * static_cast<T>(tr - tl + 1);
    node.max_v += x;
    if (node.smax_v != neg_inf()) {
      node.smax_v += x;
    }
    node.min_v += x;
    if (node.smin_v != pos_inf()) {
      node.smin_v += x;
    }
    node.add += x;
  }



  void apply_chmin(int v, const T& x) {
    Node& node = tree_[v];
    if (node.max_v <= x) {
      return;
    }
    node.sum += (x - node.max_v) * static_cast<T>(node.max_count);
    if (node.max_v == node.min_v) {
      node.max_v = node.min_v = x;
    } else if (node.max_v == node.smin_v) {
      node.max_v = node.smin_v = x;
    } else {
      node.max_v = x;
    }
  }



  void apply_chmax(int v, const T& x) {
    Node& node = tree_[v];
    if (node.min_v >= x) {
      return;
    }
    node.sum += (x - node.min_v) * static_cast<T>(node.min_count);
    if (node.max_v == node.min_v) {
      node.max_v = node.min_v = x;
    } else if (node.smax_v == node.min_v) {
      node.min_v = node.smax_v = x;
    } else {
      node.min_v = x;
    }
  }



  void push(int v, int tl, int tr) {
    if (tl == tr) {
      return;
    }
    const int tm = (tl + tr) / 2;

    if (tree_[v].add != T(0)) {
      apply_add(v * 2, tl, tm, tree_[v].add);
      apply_add(v * 2 + 1, tm + 1, tr, tree_[v].add);
      tree_[v].add = T(0);
    }


    if (tree_[v * 2].max_v > tree_[v].max_v) {
      apply_chmin(v * 2, tree_[v].max_v);
    }
    if (tree_[v * 2 + 1].max_v > tree_[v].max_v) {
      apply_chmin(v * 2 + 1, tree_[v].max_v);
    }


    if (tree_[v * 2].min_v < tree_[v].min_v) {
      apply_chmax(v * 2, tree_[v].min_v);
    }
    if (tree_[v * 2 + 1].min_v < tree_[v].min_v) {
      apply_chmax(v * 2 + 1, tree_[v].min_v);
    }

  }



  void add_rec(int v, int tl, int tr, int l, int r, const T& x) {
    if (tl > r || tr < l) {
      return;
    }
    if (l <= tl && tr <= r) {
      apply_add(v, tl, tr, x);
      return;
    }
    push(v, tl, tr);
    const int tm = (tl + tr) / 2;
    add_rec(v * 2, tl, tm, l, r, x);
    add_rec(v * 2 + 1, tm + 1, tr, l, r, x);
    pull(v);
  }



  void chmin_rec(int v, int tl, int tr, int l, int r, const T& x) {
    if (tl > r || tr < l || tree_[v].max_v <= x) {
      return;
    }
    if (l <= tl && tr <= r && tree_[v].smax_v < x) {
      apply_chmin(v, x);
      return;
    }
    push(v, tl, tr);
    const int tm = (tl + tr) / 2;
    chmin_rec(v * 2, tl, tm, l, r, x);
    chmin_rec(v * 2 + 1, tm + 1, tr, l, r, x);
    pull(v);
  }



  void chmax_rec(int v, int tl, int tr, int l, int r, const T& x) {
    if (tl > r || tr < l || tree_[v].min_v >= x) {
      return;
    }
    if (l <= tl && tr <= r && tree_[v].smin_v > x) {
      apply_chmax(v, x);
      return;
    }
    push(v, tl, tr);
    const int tm = (tl + tr) / 2;
    chmax_rec(v * 2, tl, tm, l, r, x);
    chmax_rec(v * 2 + 1, tm + 1, tr, l, r, x);
    pull(v);
  }



  T query_sum_rec(int v, int tl, int tr, int l, int r) {
    if (tl > r || tr < l) {
      return T(0);
    }
    if (l <= tl && tr <= r) {
      return tree_[v].sum;
    }

    push(v, tl, tr);

    const int tm = (tl + tr) / 2;
    return query_sum_rec(v * 2, tl, tm, l, r) +
           query_sum_rec(v * 2 + 1, tm + 1, tr, l, r);
  }



  T query_min_rec(int v, int tl, int tr, int l, int r) {
    if (tl > r || tr < l) {
      return pos_inf();
    }
    if (l <= tl && tr <= r) {
      return tree_[v].min_v;
    }

    push(v, tl, tr);

    const int tm = (tl + tr) / 2;
    return std::min(query_min_rec(v * 2, tl, tm, l, r),
                    query_min_rec(v * 2 + 1, tm + 1, tr, l, r));
  }



  T query_max_rec(int v, int tl, int tr, int l, int r) {
    if (tl > r || tr < l) {
      return neg_inf();
    }
    if (l <= tl && tr <= r) {
      return tree_[v].max_v;
    }

    push(v, tl, tr);

    const int tm = (tl + tr) / 2;
    return std::max(query_max_rec(v * 2, tl, tm, l, r),
                    query_max_rec(v * 2 + 1, tm + 1, tr, l, r));
  }

};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Apply range chmin, chmax, and add updates with aggregate queries."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  std::vector<long long> values = {5, 1, 7, 3, 9};
    SegmentTreeBeats<long long> tree(values);
    assert(tree.query_sum(0, 4) == 25);
    tree.chmin(0, 4, 6);
    assert(tree.query_max(0, 4) == 6);
    tree.chmax(1, 3, 4);
    tree.add(2, 4, -2);
    assert(tree.query_sum(0, 4) == 19);
    assert(tree.query_min(0, 4) == 2);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
