// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/kruskal

#include <bits/stdc++.h>
using namespace std;

/*
Example:
std::vector<KruskalEdge> edges;
for (int id = 0; id < m; ++id) {
  int u, v;
  long long weight;
  std::cin >> u >> v >> weight;
  edges.push_back({u, v, weight, id});
}
auto mst = kruskal(n, edges);
*/
#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

struct KruskalEdge {
  int u, v;
  long long weight;
  int id;

  friend std::ostream& operator<<(std::ostream& out, const KruskalEdge& edge) {
    return out << edge.u << ' ' << edge.v << ' ' << edge.weight << ' ' << edge.id;
  }
};

struct KruskalResult {
  long long weight;
  std::vector<KruskalEdge> edges;
  bool connected;
};

KruskalResult kruskal(int n, std::vector<KruskalEdge> edges) {
  std::sort(edges.begin(), edges.end(), [](const KruskalEdge& a, const KruskalEdge& b) {
    if (a.weight != b.weight) return a.weight < b.weight;
    return a.id < b.id;
  });

  std::vector<int> parent(n), size(n, 1);
  std::iota(parent.begin(), parent.end(), 0);
  EDULCNI_VIS(([&] {
    std::vector<std::pair<int, int>> graph_edges;
    for (const auto& edge : edges) graph_edges.push_back({edge.u, edge.v});
    edulcni::live::edges("kruskal.graph", n, graph_edges);
  }()));
  EDULCNI_STEP("Kruskal initialized");

  auto find = [&](auto&& self, int v) -> int {
    return parent[v] == v ? v : parent[v] = self(self, parent[v]);
  };

  KruskalResult result{0, {}, n <= 1};
  result.edges.reserve(n > 0 ? n - 1 : 0);

  for (const auto& edge : edges) {
    int u = find(find, edge.u);
    int v = find(find, edge.v);
    if (u == v) continue;

    if (size[u] < size[v]) std::swap(u, v);
    parent[v] = u;
    size[u] += size[v];
    result.weight += edge.weight;
    result.edges.push_back(edge);
    EDULCNI_VIS(edulcni::live::forest("kruskal.forest", parent));
    EDULCNI_VIS(edulcni::live::graph_focus(
        "kruskal.graph", std::vector<int>{edge.u, edge.v},
        std::vector<std::pair<int, int>>{
            std::make_pair(edge.u, edge.v)},
        edulcni::live::FocusRole::accepted,
        "edge joins two components"));
    EDULCNI_STEP("Kruskal accepts an edge");
  }

  result.connected = n <= 1 || static_cast<int>(result.edges.size()) == n - 1;
  EDULCNI_VIS(([&] {
    std::vector<int> vertices;
    std::vector<std::pair<int, int>> selected;
    for (const auto& edge : result.edges) {
      vertices.push_back(edge.u);
      vertices.push_back(edge.v);
      selected.push_back({edge.u, edge.v});
    }
    edulcni::live::graph_focus(
        "kruskal.graph", vertices, selected,
        edulcni::live::FocusRole::result,
        result.connected ? "minimum spanning tree" : "minimum spanning forest");
  }()));
  EDULCNI_STEP("Kruskal completed");
  return result;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Build a minimum spanning tree and recover its selected edges."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  const std::vector<KruskalEdge> edges = {
        {0, 1, 1, 0},
        {1, 2, 2, 1},
        {0, 2, 4, 2},
    };
    const auto result = kruskal(3, edges);
    assert(result.connected);
    assert(result.weight == 3);
    assert(result.edges.size() == 2);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
