// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/fft_ntt

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif


inline int fft_next_power_of_two(int n) {
  int p = 1;
  while (p < n) {
    p <<= 1;
  }
  return p;
}

inline bool fft_is_power_of_two(int n) { return n > 0 && (n & (n - 1)) == 0; }

template <typename T>
inline void fft_bit_reverse(std::vector<T>& a) {
  const int n = static_cast<int>(a.size());
  for (int i = 1, j = 0; i < n; ++i) {
    int bit = n >> 1;
    while (j & bit) {
      j ^= bit;
      bit >>= 1;
    }
    j ^= bit;
    if (i < j) {
      std::swap(a[i], a[j]);
    }
  }
}


inline int ntt_pow(int a, long long e, int mod) {
  long long res = 1;
  long long base = a % mod;
  if (base < 0) {
    base += mod;
  }
  while (e > 0) {
    if (e & 1LL) {
      res = res * base % mod;
    }
    base = base * base % mod;
    e >>= 1LL;
  }
  return static_cast<int>(res);
}

inline bool ntt_transform(std::vector<int>& a, bool invert = false,
                          int mod = 998244353, int primitive_root = 3) {
  const int n = static_cast<int>(a.size());
  if (n == 0) {
    return true;
  }
  if (!fft_is_power_of_two(n) || (mod - 1) % n != 0) {
    return false;
  }

  fft_bit_reverse(a);
  EDULCNI_VIS(edulcni::live::array("ntt.values", a));
  EDULCNI_STEP("NTT bit-reversal completed");
  for (int len = 2; len <= n; len <<= 1) {
    int wlen = ntt_pow(primitive_root, (mod - 1) / len, mod);
    if (invert) {
      wlen = ntt_pow(wlen, mod - 2, mod);
    }
    for (int i = 0; i < n; i += len) {
      long long w = 1;
      for (int j = 0; j < len / 2; ++j) {
        const int u = a[i + j];
        const int v = static_cast<int>(w * a[i + j + len / 2] % mod);
        int x = u + v;
        if (x >= mod) {
          x -= mod;
        }
        int y = u - v;
        if (y < 0) {
          y += mod;
        }
        a[i + j] = x;
        a[i + j + len / 2] = y;
        w = w * wlen % mod;
      }
    }
    EDULCNI_VIS(edulcni::live::array("ntt.values", a));
    EDULCNI_STEP("NTT completed a butterfly stage");
  }

  if (invert) {
    const int inv_n = ntt_pow(n, mod - 2, mod);
    for (int& x : a) {
      x = static_cast<int>(1LL * x * inv_n % mod);
    }
  }
  return true;
}

template <typename T>
inline std::vector<int> convolution_ntt_int(const std::vector<T>& a,
                                            const std::vector<T>& b,
                                            int mod = 998244353,
                                            int primitive_root = 3) {
  if (a.empty() || b.empty()) {
    return {};
  }
  const int need = static_cast<int>(a.size() + b.size() - 1);
  const int n = fft_next_power_of_two(need);
  std::vector<int> fa(n), fb(n);
  for (int i = 0; i < static_cast<int>(a.size()); ++i) {
    long long x = static_cast<long long>(a[i]) % mod;
    if (x < 0) {
      x += mod;
    }
    fa[i] = static_cast<int>(x);
  }
  for (int i = 0; i < static_cast<int>(b.size()); ++i) {
    long long x = static_cast<long long>(b[i]) % mod;
    if (x < 0) {
      x += mod;
    }
    fb[i] = static_cast<int>(x);
  }

  if (!ntt_transform(fa, false, mod, primitive_root) ||
      !ntt_transform(fb, false, mod, primitive_root)) {
    return {};
  }
  for (int i = 0; i < n; ++i) {
    fa[i] = static_cast<int>(1LL * fa[i] * fb[i] % mod);
  }
  if (!ntt_transform(fa, true, mod, primitive_root)) {
    return {};
  }
  fa.resize(need);
  return fa;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Multiply two integer polynomials with the NTT."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  const std::vector<int> a = {1, 2, 3, 4};
    const std::vector<int> b = {5, 6, 7};
    const std::vector<int> product = convolution_ntt_int(a, b);
    assert((product == std::vector<int>{5, 16, 34, 52, 45, 28}));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
