// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/test_generators

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

struct TestGenerator {
  std::mt19937_64 rng;

  explicit TestGenerator(uint64_t seed = std::chrono::steady_clock::now().time_since_epoch().count())
      : rng(seed) {}

  template <class T>
  T generate_integer(T low, T high) {
    return std::uniform_int_distribution<T>(low, high)(rng);
  }

  template <class T>
  std::vector<T> generate_array(int n, T low, T high) {
    std::vector<T> result(n);
    for (auto& value : result) value = generate_integer<T>(low, high);
    EDULCNI_VIS(edulcni::live::array("generator.array", result));
    EDULCNI_STEP("Random array generated");
    return result;
  }

  std::vector<int> generate_permutation(int n, int first = 0) {
    std::vector<int> result(n);
    std::iota(result.begin(), result.end(), first);
    std::shuffle(result.begin(), result.end(), rng);
    EDULCNI_VIS(edulcni::live::array("generator.permutation", result));
    EDULCNI_STEP("Random permutation generated");
    return result;
  }

  uint64_t generate_mask(int bits) {
    if (bits <= 0) return 0;
    if (bits >= 64) return rng();
    const uint64_t result = generate_integer<uint64_t>(0, (uint64_t(1) << bits) - 1);
    EDULCNI_VIS(edulcni::live::bits("generator.mask", result, bits));
    EDULCNI_STEP("Random mask generated");
    return result;
  }

  std::vector<uint64_t> generate_masks(int count, int bits) {
    std::vector<uint64_t> result(count);
    for (auto& value : result) value = generate_mask(bits);
    EDULCNI_VIS(edulcni::live::array("generator.masks", result));
    EDULCNI_STEP("Random masks generated");
    return result;
  }

  std::string generate_string(int n, std::string_view alphabet = "abcdefghijklmnopqrstuvwxyz") {
    assert(!alphabet.empty());
    std::string result(n, ' ');
    for (char& ch : result) ch = alphabet[generate_integer<int>(0, int(alphabet.size()) - 1)];
    EDULCNI_VIS(edulcni::live::array("generator.string", result));
    EDULCNI_STEP("Random string generated");
    return result;
  }

  std::vector<std::pair<int, int>> generate_tree(int n, int first = 0) {
    if (n <= 1) return {};
    auto order = generate_permutation(n, first);
    std::vector<std::pair<int, int>> edges;
    edges.reserve(n - 1);
    for (int i = 1; i < n; ++i) {
      int parent = order[generate_integer<int>(0, i - 1)];
      edges.push_back({parent, order[i]});
    }
    std::shuffle(edges.begin(), edges.end(), rng);
    EDULCNI_VIS(edulcni::live::edges("generator.tree", n + first, edges));
    EDULCNI_STEP("Random tree generated");
    return edges;
  }

  std::vector<std::pair<int, int>> generate_graph(int n, int m, bool connected = false, int first = 0) {
    int maximum = n * (n - 1) / 2;
    assert(0 <= m && m <= maximum);
    assert(!connected || n == 0 || m >= n - 1);
    std::set<std::pair<int, int>> selected;
    if (connected) {
      for (auto [u, v] : generate_tree(n, first)) {
        if (u > v) std::swap(u, v);
        selected.insert({u, v});
      }
    }
    while (int(selected.size()) < m) {
      int u = generate_integer(first, first + n - 1);
      int v = generate_integer(first, first + n - 1);
      if (u == v) continue;
      if (u > v) std::swap(u, v);
      selected.insert({u, v});
    }
    std::vector<std::pair<int, int>> edges(selected.begin(), selected.end());
    std::shuffle(edges.begin(), edges.end(), rng);
    EDULCNI_VIS(edulcni::live::edges("generator.graph", n + first, edges));
    EDULCNI_STEP("Random graph generated");
    return edges;
  }
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Generate deterministic arrays, permutations, masks, trees, and graphs."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  TestGenerator generator(123456789);
    const auto values = generator.generate_array<int>(6, -5, 5);
    assert(values.size() == 6);
    assert(std::all_of(values.begin(), values.end(), [](int value) {
      return -5 <= value && value <= 5;
    }));

    auto permutation = generator.generate_permutation(6);
    std::sort(permutation.begin(), permutation.end());
    assert((permutation == std::vector<int>{0, 1, 2, 3, 4, 5}));

    const auto tree = generator.generate_tree(6);
    assert(tree.size() == 5);
    const auto graph = generator.generate_graph(6, 7, true);
    assert(graph.size() == 7);
    assert(generator.generate_mask(5) < (std::uint64_t{1} << 5));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
