// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/fenwick

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename T>
struct FenwickSumOp {
  static constexpr bool kHasInverse = true;
  static constexpr bool kHasDescend = true;

  static T default_neutral() { return T(0); }
  static T combine(const T& lhs, const T& rhs) { return lhs + rhs; }
  static T inverse(const T& total, const T& prefix) { return total - prefix; }
  static bool descend_should_advance(const T& candidate, const T& target) {
    return candidate < target;
  }
};












template <typename T, typename Op>
class Fenwick {
 public:
  explicit Fenwick(int n = 0, const T& neutral = Op::default_neutral())
      : n_(n < 0 ? 0 : n),
        maxn_(n_ + 1),
        bit_(maxn_, neutral),
        neutral_(neutral) {}

  void reset(int n, const T& neutral = Op::default_neutral()) {
    n_ = (n < 0 ? 0 : n);
    maxn_ = n_ + 1;
    neutral_ = neutral;
    bit_.assign(maxn_, neutral_);
    EDULCNI_VIS(edulcni::live::array("fenwick.tree", bit_));
    EDULCNI_STEP("Fenwick tree reset");
  }

  int size() const { return n_; }

  void add(int idx, const T& value) {
    if (idx < 0 || idx >= n_) {
      return;
    }
    for (int i = idx + 1; i < maxn_; i += i & -i) {
      bit_[i] = Op::combine(bit_[i], value);
    }
    EDULCNI_VIS(edulcni::live::array("fenwick.tree", bit_));
    EDULCNI_VIS(([&] {
      std::vector<int> changed;
      for (int i = idx + 1; i < maxn_; i += i & -i) {
        changed.push_back(i);
      }
      edulcni::live::array_focus(
          "fenwick.tree", changed, edulcni::live::FocusRole::changed,
          "updated Fenwick ancestors");
      int width = 1;
      for (int value = n_; value > 1; value >>= 1) {
        ++width;
      }
      edulcni::live::bits(
          "fenwick.index", static_cast<std::uint64_t>(idx + 1), width);
    })());
    EDULCNI_STEP("Fenwick tree updated");
  }

  T prefix(int idx) const {
    if (idx < 0) {
      return neutral_;
    }
    if (idx >= n_) {
      idx = n_ - 1;
    }
    T result = neutral_;
    for (int i = idx + 1; i > 0; i -= i & -i) {
      result = Op::combine(result, bit_[i]);
    }
    EDULCNI_VIS(([&] {
      std::vector<int> visited;
      for (int i = idx + 1; i > 0; i -= i & -i) visited.push_back(i);
      edulcni::live::array("fenwick.tree", bit_);
      edulcni::live::array_focus(
          "fenwick.tree", visited, edulcni::live::FocusRole::result,
          "nodes combined for the prefix");
    }()));
    EDULCNI_STEP("Fenwick tree answered a prefix query");
    return result;
  }

  T segment(int left, int right) const {
    static_assert(Op::kHasInverse,
                  "segment query requires an invertible operation");
    if (left > right) {
      return neutral_;
    }
    if (right < 0 || left >= n_) {
      return neutral_;
    }
    if (left < 0) {
      left = 0;
    }
    if (right >= n_) {
      right = n_ - 1;
    }
    return Op::inverse(prefix(right), prefix(left - 1));
  }

  int descend(const T& target) const {
    static_assert(Op::kHasDescend,
                  "descend is not defined for this operation");
    if (n_ == 0) {
      return 0;
    }

    int pos = 0;
    T accumulated = neutral_;

    int pw = 1;
    while ((pw << 1) < maxn_) {
      pw <<= 1;
    }

    for (; pw > 0; pw >>= 1) {
      const int next = pos + pw;
      if (next >= maxn_) {
        continue;
      }
      const T candidate = Op::combine(accumulated, bit_[next]);
      if (Op::descend_should_advance(candidate, target)) {
        pos = next;
        accumulated = candidate;
      }
    }
    return pos;
  }

 private:
  int n_;
  int maxn_;
  std::vector<T> bit_;
  T neutral_;
};


template <typename T>
using FenwickSumTree = Fenwick<T, FenwickSumOp<T>>;

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Accumulate point additions and query prefix and range sums."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  FenwickSumTree<int> tree(6);
    const std::vector<int> values = {3, 1, 4, 1, 5, 9};
    for (int i = 0; i < static_cast<int>(values.size()); ++i) tree.add(i, values[i]);
    assert(tree.prefix(3) == 9);
    assert(tree.segment(2, 5) == 19);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
