// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/divide_conquer_dp

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename Cost>
inline void divide_conquer_dp_layer(const std::vector<long long>& previous,
                                    std::vector<long long>& current,
                                    int left, int right, int opt_left,
                                    int opt_right, Cost cost) {
  if (left > right) return;
  const int middle = (left + right) / 2;
  std::pair<long long, int> best = {std::numeric_limits<long long>::max(), -1};
  for (int split = opt_left; split <= std::min(middle, opt_right); ++split) {
    if (previous[split] == std::numeric_limits<long long>::max()) continue;
    best = std::min(best, {previous[split] + cost(split, middle), split});
  }
  current[middle] = best.first;
  EDULCNI_VIS(edulcni::live::array("divide_conquer_dp.previous", previous));
  EDULCNI_VIS(edulcni::live::array("divide_conquer_dp.current", current));
  EDULCNI_VIS(edulcni::live::array(
      "divide_conquer_dp.range", std::vector<int>{left, middle, right}));
  EDULCNI_VIS(edulcni::live::value("divide_conquer_dp.optimum", best.second));
  EDULCNI_STEP("Divide-and-conquer DP computes a midpoint");
  if (left == right) return;
  divide_conquer_dp_layer(previous, current, left, middle - 1,
                          opt_left, best.second, cost);
  divide_conquer_dp_layer(previous, current, middle + 1, right,
                          best.second, opt_right, cost);
}

template <typename Cost>
inline std::vector<long long> divide_conquer_partition_dp(int n, int groups,
                                                          Cost cost) {
  const long long infinity = std::numeric_limits<long long>::max();
  std::vector<long long> previous(n + 1, infinity), current(n + 1, infinity);
  previous[0] = 0;
  EDULCNI_VIS(edulcni::live::array("divide_conquer_dp.previous", previous));
  EDULCNI_STEP("Divide-and-conquer DP initialized");
  for (int group = 1; group <= groups; ++group) {
    std::fill(current.begin(), current.end(), infinity);
    divide_conquer_dp_layer(previous, current, group, n, group - 1, n - 1, cost);
    previous.swap(current);
    EDULCNI_VIS(edulcni::live::array("divide_conquer_dp.previous", previous));
    EDULCNI_VIS(edulcni::live::value("divide_conquer_dp.group", group));
    EDULCNI_STEP("Divide-and-conquer DP completes a layer");
  }
  return previous;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  const auto squared_length = [](int left, int right) {
      const long long length = right - left;
      return length * length;
    };
    const auto result = divide_conquer_partition_dp(5, 2, squared_length);
    assert(result[5] == 13);

  cout << "ok\n";
  return 0;
}
