// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/substring_dp

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename Cost>
inline std::pair<Cost, std::vector<std::pair<int, int>>> substring_partition_dp(
    int n, Cost infinity, const std::function<Cost(int, int)>& segment_cost) {
  std::vector<Cost> dp(n + 1, infinity);
  std::vector<int> parent(n + 1, -1);
  dp[0] = Cost{};
  EDULCNI_VIS(edulcni::live::array("substring_partition.dp", dp));
  EDULCNI_STEP("Substring partition DP initialized");
  for (int right = 1; right <= n; ++right) {
    for (int left = 0; left < right; ++left) {
      const Cost candidate = dp[left] + segment_cost(left, right);
      if (candidate < dp[right]) dp[right] = candidate, parent[right] = left;
    }
    EDULCNI_VIS(edulcni::live::array("substring_partition.dp", dp));
    EDULCNI_VIS(edulcni::live::array("substring_partition.parent", parent));
    EDULCNI_VIS(edulcni::live::value("substring_partition.right", right));
    EDULCNI_STEP("Substring partition DP completes an endpoint");
  }
  std::vector<std::pair<int, int>> parts;
  for (int right = n; right > 0 && parent[right] != -1; right = parent[right])
    parts.push_back({parent[right], right});
  std::reverse(parts.begin(), parts.end());
  EDULCNI_VIS(edulcni::live::array("substring_partition.dp", dp));
  EDULCNI_STEP("Substring partition reconstructed");
  return {dp[n], parts};
}

inline int longest_palindromic_subsequence(const std::string& text) {
  const int n = static_cast<int>(text.size());
  if (n == 0) return 0;
  std::vector<std::vector<int>> dp(n, std::vector<int>(n));
  EDULCNI_VIS(edulcni::live::array("palindrome.text", text));
  EDULCNI_STEP("Palindromic subsequence DP initialized");
  for (int left = n - 1; left >= 0; --left) {
    dp[left][left] = 1;
    for (int right = left + 1; right < n; ++right)
      dp[left][right] = text[left] == text[right]
          ? 2 + (right - left == 1 ? 0 : dp[left + 1][right - 1])
          : std::max(dp[left + 1][right], dp[left][right - 1]);
    EDULCNI_VIS(edulcni::live::matrix("palindrome.dp", dp));
    EDULCNI_VIS(edulcni::live::value("palindrome.left", left));
    EDULCNI_STEP("Palindromic subsequence DP completes a row");
  }
  return dp[0][n - 1];
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  const std::string text = "aab";
    const std::function<long long(int, int)> palindrome_cost =
        [&](int left, int right) {
          const std::string part = text.substr(left, right - left);
          return std::equal(part.begin(), part.end(), part.rbegin()) ? 1LL : 1000LL;
        };
    const auto partition = substring_partition_dp<long long>(
        static_cast<int>(text.size()), 1000000LL, palindrome_cost);
    assert(partition.first == 2);
    assert((partition.second == std::vector<std::pair<int, int>>{{0, 2}, {2, 3}}));
    assert(longest_palindromic_subsequence("bbbab") == 4);

  cout << "ok\n";
  return 0;
}
