// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/segtree

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

template <typename T>
class SegmentTree {
 public:
  explicit SegmentTree(int n = 0) { reset(n); }
  explicit SegmentTree(const std::vector<T>& values) { build(values); }

  void reset(int n) {
    n_ = std::max(0, n);
    tree_.assign(4 * std::max(1, n_), neutral());
    trace("Segment tree reset");
  }
  void build(const std::vector<T>& values) {
    reset(static_cast<int>(values.size()));
    if (n_ > 0) build_rec(1, 0, n_ - 1, values);
    trace("Segment tree built");
  }
  int size() const { return n_; }

  T query(int left, int right) const {
    if (!normalize(left, right)) return neutral();
    const T result = query_rec(1, 0, n_ - 1, left, right);
    trace_range("Segment tree queried a range", left, right, false);
    return result;
  }

  template <typename Predicate>
  int find_first(int left, int right, Predicate can_contain) const {
    if (!normalize(left, right)) return -1;
    return find_first_predicate_rec(1, 0, n_ - 1, left, right, can_contain);
  }

  template <typename Predicate>
  int find_last(int left, int right, Predicate can_contain) const {
    if (!normalize(left, right)) return -1;
    return find_last_predicate_rec(1, 0, n_ - 1, left, right, can_contain);
  }

  void point_set(int position, const T& value) {
    if (position < 0 || position >= n_) return;
    point_set_rec(1, 0, n_ - 1, position, value);
    trace_range("Segment tree updated a point", position, position, true);
  }







 private:
  int n_ = 0;
  std::vector<T> tree_;
  static T neutral() { return int(0); }
  static T merge(const T& left, const T& right) { return left + right; }
  bool normalize(int& left, int& right) const {
    if (n_ == 0 || left > right || right < 0 || left >= n_) return false;
    left = std::max(left, 0); right = std::min(right, n_ - 1); return left <= right;
  }
  void build_rec(int v, int tl, int tr, const std::vector<T>& values) {
    if (tl == tr) { tree_[v] = values[tl]; return; }
    const int tm = (tl + tr) / 2;
    build_rec(v * 2, tl, tm, values); build_rec(v * 2 + 1, tm + 1, tr, values);
    tree_[v] = merge(tree_[v * 2], tree_[v * 2 + 1]);
  }
  T query_rec(int v, int tl, int tr, int l, int r) const {
    if (tl > r || tr < l) return neutral();
    if (l <= tl && tr <= r) return tree_[v];
    const int tm = (tl + tr) / 2;
    return merge(query_rec(v * 2, tl, tm, l, r), query_rec(v * 2 + 1, tm + 1, tr, l, r));
  }
  template <typename Predicate>
  int find_first_predicate_rec(int v, int tl, int tr, int l, int r,
                               Predicate can_contain) const {
    if (tl > r || tr < l || !can_contain(tree_[v])) return -1;
    if (tl == tr) return tl;
    const int tm = (tl + tr) / 2;
    int found = find_first_predicate_rec(v * 2, tl, tm, l, r, can_contain);
    return found != -1 ? found
                       : find_first_predicate_rec(v * 2 + 1, tm + 1, tr, l, r,
                                                  can_contain);
  }
  template <typename Predicate>
  int find_last_predicate_rec(int v, int tl, int tr, int l, int r,
                              Predicate can_contain) const {
    if (tl > r || tr < l || !can_contain(tree_[v])) return -1;
    if (tl == tr) return tl;
    const int tm = (tl + tr) / 2;
    int found = find_last_predicate_rec(v * 2 + 1, tm + 1, tr, l, r, can_contain);
    return found != -1 ? found
                       : find_last_predicate_rec(v * 2, tl, tm, l, r, can_contain);
  }

  void point_set_rec(int v, int tl, int tr, int p, const T& value) {
    if (tl == tr) { tree_[v] = value; return; }
    const int tm = (tl + tr) / 2;
    if (p <= tm) point_set_rec(v * 2, tl, tm, p, value);
    else point_set_rec(v * 2 + 1, tm + 1, tr, p, value);
    tree_[v] = merge(tree_[v * 2], tree_[v * 2 + 1]);
  }



  void trace(const char* label) const {
    EDULCNI_VIS(edulcni::live::segment_tree("segtree.tree", static_cast<std::size_t>(n_), tree_));
    EDULCNI_STEP(label);
  }
  void trace_range(const char* label, int left, int right, bool changed) const {
    EDULCNI_VIS(edulcni::live::segment_tree("segtree.tree", static_cast<std::size_t>(n_), tree_));
    EDULCNI_VIS(edulcni::live::segment_tree_range_focus(
        "segtree.tree", static_cast<std::size_t>(n_), left, right,
        changed ? edulcni::live::FocusRole::changed : edulcni::live::FocusRole::result,
        "active inclusive range"));
    EDULCNI_STEP(label);
  }
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Point updates and inclusive range sums in the standard segment-tree scenario."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  std::vector<int> values = {1, 2, 3, 4};
    SegmentTree<int> tree(values);
    assert(tree.query(0, 3) == 10);
    tree.point_set(2, 10);
    assert(tree.query(1, 3) == 16);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
