// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/bfs

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

struct BfsResult {
  std::vector<int> distance;
  std::vector<int> parent;
  std::vector<int> order;
};

inline void bfs_add_edge(std::vector<std::vector<int>>& graph, int from, int to,
                         bool undirected = false) {
  const int n = static_cast<int>(graph.size());
  if (from < 0 || from >= n || to < 0 || to >= n) {
    return;
  }
  graph[from].push_back(to);
  if (undirected && from != to) {
    graph[to].push_back(from);
  }
}

inline BfsResult bfs_multi_source(const std::vector<std::vector<int>>& graph,
                                  const std::vector<int>& sources) {
  const int n = static_cast<int>(graph.size());
  BfsResult result;
  result.distance.assign(n, -1);
  result.parent.assign(n, -1);
  result.order.clear();

  std::queue<int> q;
  for (int source : sources) {
    if (source < 0 || source >= n || result.distance[source] != -1) {
      continue;
    }
    result.distance[source] = 0;
    result.order.push_back(source);
    q.push(source);
  }

  EDULCNI_VIS(edulcni::live::graph("bfs.graph", graph));
  EDULCNI_VIS(edulcni::live::array("bfs.distance", result.distance));
  EDULCNI_VIS(edulcni::live::array("bfs.parent", result.parent));
  EDULCNI_VIS(edulcni::live::queue("bfs.frontier", q));
  EDULCNI_STEP("BFS initialized");

  while (!q.empty()) {
    const int v = q.front();
    q.pop();
    EDULCNI_VIS(edulcni::live::graph_focus(
        "bfs.graph", std::vector<int>{v},
        std::vector<std::pair<int, int>>{},
        edulcni::live::FocusRole::active, "vertex removed from frontier"));
    EDULCNI_VIS(edulcni::live::queue("bfs.frontier", q));
    EDULCNI_STEP("BFS visits a vertex");

    for (int to : graph[v]) {
      if (to < 0 || to >= n || result.distance[to] != -1) {
        continue;
      }
      result.distance[to] = result.distance[v] + 1;
      result.parent[to] = v;
      result.order.push_back(to);
      q.push(to);
      EDULCNI_VIS(edulcni::live::array("bfs.distance", result.distance));
      EDULCNI_VIS(edulcni::live::array("bfs.parent", result.parent));
      EDULCNI_VIS(edulcni::live::queue("bfs.frontier", q));
      EDULCNI_VIS(edulcni::live::graph_focus(
          "bfs.graph", std::vector<int>{v, to},
          std::vector<std::pair<int, int>>{std::make_pair(v, to)},
          edulcni::live::FocusRole::accepted,
          "edge discovers an unvisited vertex"));
      EDULCNI_VIS(edulcni::live::array_focus(
          "bfs.distance", to, edulcni::live::FocusRole::changed,
          "distance assigned"));
      EDULCNI_VIS(edulcni::live::array_focus(
          "bfs.parent", to, edulcni::live::FocusRole::changed,
          "parent assigned"));
      EDULCNI_STEP("BFS discovers a vertex");
    }
  }

  return result;
}

inline BfsResult bfs(const std::vector<std::vector<int>>& graph, int source) {
  return bfs_multi_source(graph, std::vector<int>(1, source));
}

inline std::vector<int> bfs_restore_path(int source, int target,
                                         const BfsResult& result) {
  const int n = static_cast<int>(result.parent.size());
  if (source < 0 || source >= n || target < 0 || target >= n) {
    return {};
  }

  std::vector<int> path;
  int current = target;
  int steps = 0;
  while (current != -1 && steps <= n) {
    path.push_back(current);
    current = result.parent[current];
    ++steps;
  }

  if (path.empty() || path.back() != source) {
    return {};
  }
  std::reverse(path.begin(), path.end());
  EDULCNI_VIS(edulcni::live::graph_path_focus(
      "bfs.graph", path, edulcni::live::FocusRole::result,
      "restored shortest unweighted path"));
  EDULCNI_STEP("BFS restored a path");
  return path;
}

inline std::vector<int> bfs_restore_path_to_root(int target,
                                                 const BfsResult& result) {
  const int n = static_cast<int>(result.parent.size());
  if (target < 0 || target >= n || result.distance[target] == -1) {
    return {};
  }

  std::vector<int> path;
  int current = target;
  int steps = 0;
  while (current != -1 && steps <= n) {
    path.push_back(current);
    current = result.parent[current];
    ++steps;
  }
  std::reverse(path.begin(), path.end());
  return path;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Explore an unweighted graph and restore a shortest path."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  std::vector<std::vector<int>> graph(6);
    bfs_add_edge(graph, 0, 1, true);
    bfs_add_edge(graph, 1, 2, true);
    bfs_add_edge(graph, 2, 3, true);
    bfs_add_edge(graph, 1, 4, true);
    bfs_add_edge(graph, 4, 5, true);
    const BfsResult result = bfs(graph, 0);
    assert(result.distance[5] == 3);
    const auto path = bfs_restore_path(0, 5, result);
    assert((path == std::vector<int>{0, 1, 4, 5}));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
