// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/monotone_queue_dp

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

inline std::vector<long long> sliding_window_min_dp(
    const std::vector<long long>& transition_cost, int window) {
  const int n = static_cast<int>(transition_cost.size());
  if (n == 0 || window <= 0) return {};
  std::vector<long long> dp(n);
  std::deque<int> candidates;
  EDULCNI_VIS(edulcni::live::array("monotone_queue.cost", transition_cost));
  EDULCNI_STEP("Monotone queue DP initialized");
  for (int i = 0; i < n; ++i) {
    while (!candidates.empty() && candidates.front() < i - window)
      candidates.pop_front();
    if (i > 0) dp[i] = dp[candidates.front()] + transition_cost[i];
    while (!candidates.empty() && dp[candidates.back()] >= dp[i])
      candidates.pop_back();
    candidates.push_back(i);
    EDULCNI_VIS(edulcni::live::array("monotone_queue.dp", dp));
    EDULCNI_VIS(edulcni::live::array("monotone_queue.candidates", candidates));
    EDULCNI_VIS(edulcni::live::value("monotone_queue.index", i));
    EDULCNI_STEP("Monotone queue DP processes a position");
  }
  return dp;
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  const std::vector<long long> transition_cost = {0, 5, 1, 2, 10, 1};
    const auto result = sliding_window_min_dp(transition_cost, 2);
    assert((result == std::vector<long long>{0, 5, 1, 3, 11, 4}));

  cout << "ok\n";
  return 0;
}
