// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/kuhn

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

struct KuhnResult {
  int matching_size;
  std::vector<int> match_left;
  std::vector<int> match_right;

  KuhnResult() : matching_size(0) {}
};

class KuhnMatcher {
 public:
  explicit KuhnMatcher(int n_left = 0, int n_right = 0) : n_left_(0), n_right_(0) {
    reset(n_left, n_right);
  }

  void reset(int n_left, int n_right) {
    n_left_ = (n_left < 0 ? 0 : n_left);
    n_right_ = (n_right < 0 ? 0 : n_right);
    graph_.assign(n_left_, std::vector<int>());
    used_.assign(n_left_, 0);
    visit_token_ = 1;
    trace("Kuhn matcher reset");
  }

  int left_size() const { return n_left_; }

  int right_size() const { return n_right_; }

  const std::vector<std::vector<int>>& graph() const { return graph_; }

  int add_edge(int left, int right) {
    if (!left_ok(left) || !right_ok(right)) {
      return -1;
    }
    graph_[left].push_back(right);
    trace("Kuhn edge added");
    return static_cast<int>(graph_[left].size()) - 1;
  }

  KuhnResult maximum_matching() {
    KuhnResult result;
    result.match_left.assign(n_left_, -1);
    result.match_right.assign(n_right_, -1);
    result.matching_size = 0;
    if (n_left_ == 0 || n_right_ == 0) {
      return result;
    }

    for (int left = 0; left < n_left_; ++left) {
      for (int right : graph_[left]) {
        if (!right_ok(right) || result.match_right[right] != -1) {
          continue;
        }
        result.match_left[left] = right;
        result.match_right[right] = left;
        ++result.matching_size;
        EDULCNI_VIS(edulcni::live::array("kuhn.match_left", result.match_left));
        EDULCNI_VIS(edulcni::live::array("kuhn.match_right", result.match_right));
        EDULCNI_STEP("Kuhn greedily matched a vertex");
        break;
      }
    }

    std::fill(used_.begin(), used_.end(), 0);
    visit_token_ = 1;
    for (int left = 0; left < n_left_; ++left) {
      if (result.match_left[left] != -1) {
        continue;
      }
      ++visit_token_;
      if (visit_token_ == std::numeric_limits<int>::max()) {
        std::fill(used_.begin(), used_.end(), 0);
        visit_token_ = 1;
      }
      if (try_augment(left, result.match_left, result.match_right)) {
        ++result.matching_size;
        EDULCNI_VIS(edulcni::live::array("kuhn.match_left", result.match_left));
        EDULCNI_VIS(edulcni::live::array("kuhn.match_right", result.match_right));
        EDULCNI_STEP("Kuhn augmented the matching");
      }
    }
    EDULCNI_STEP("Kuhn matching completed");
    return result;
  }

 private:
  int n_left_;
  int n_right_;
  std::vector<std::vector<int>> graph_;
  std::vector<int> used_;
  int visit_token_;

  void trace(const char* label) const {
    EDULCNI_VIS(edulcni::live::bipartite_graph(
        "kuhn.graph", graph_, n_right_));
    EDULCNI_STEP(label);
  }

  bool left_ok(int v) const { return v >= 0 && v < n_left_; }

  bool right_ok(int v) const { return v >= 0 && v < n_right_; }

  bool try_augment(int left, std::vector<int>& match_left, std::vector<int>& match_right) {
    if (!left_ok(left) || used_[left] == visit_token_) {
      return false;
    }
    used_[left] = visit_token_;

    for (int right : graph_[left]) {
      if (!right_ok(right)) {
        continue;
      }
      const int matched_left = match_right[right];
      if (matched_left == -1 || try_augment(matched_left, match_left, match_right)) {
        match_left[left] = right;
        match_right[right] = left;
        return true;
      }
    }
    return false;
  }
};

inline KuhnResult kuhn_maximum_matching(const std::vector<std::vector<int>>& graph,
                                        int right_size) {
  KuhnMatcher matcher(static_cast<int>(graph.size()), right_size);
  for (int left = 0; left < static_cast<int>(graph.size()); ++left) {
    for (int right : graph[left]) {
      matcher.add_edge(left, right);
    }
  }
  return matcher.maximum_matching();
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Find a maximum matching in a bipartite graph."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  KuhnMatcher matcher(3, 3);
    matcher.add_edge(0, 0);
    matcher.add_edge(0, 1);
    matcher.add_edge(1, 1);
    matcher.add_edge(2, 1);
    matcher.add_edge(2, 2);
    const auto result = matcher.maximum_matching();
    assert(result.matching_size == 3);

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
