// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /templates/poly_hash

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

constexpr int POLY_HASH_MOD1 = 1000000007;
constexpr int POLY_HASH_MOD2 = 1000000009;
constexpr int POLY_HASH_BASE = 911382323;

struct PolyHashValue {
  int first;
  int second;

  PolyHashValue(int first_ = 0, int second_ = 0)
      : first(first_), second(second_) {}
};

inline bool operator==(const PolyHashValue& lhs, const PolyHashValue& rhs) {
  return lhs.first == rhs.first && lhs.second == rhs.second;
}

inline bool operator!=(const PolyHashValue& lhs, const PolyHashValue& rhs) {
  return !(lhs == rhs);
}

inline bool operator<(const PolyHashValue& lhs, const PolyHashValue& rhs) {
  if (lhs.first != rhs.first) {
    return lhs.first < rhs.first;
  }
  return lhs.second < rhs.second;
}

class PolyHash {
 public:
  explicit PolyHash(const std::string& text = std::string(), int base = POLY_HASH_BASE) {
    build(text, base);
  }

  explicit PolyHash(const std::vector<int>& values, int base = POLY_HASH_BASE) {
    build(values, base);
  }

  void build(const std::string& text, int base = POLY_HASH_BASE) {
    std::vector<int> values;
    values.reserve(text.size());
    for (unsigned char ch : text) {
      values.push_back(static_cast<int>(ch));
    }
    build_values(values, base);
    EDULCNI_VIS(edulcni::live::text("poly_hash.text", text));
    EDULCNI_STEP("Polynomial hash built from text");
  }

  void build(const std::vector<int>& values, int base = POLY_HASH_BASE) {
    build_values(values, base);
    EDULCNI_VIS(edulcni::live::array("poly_hash.values", values));
    EDULCNI_STEP("Polynomial hash built from values");
  }

  int size() const { return static_cast<int>(prefix1_.size()) - 1; }

  int base() const { return base_; }

  PolyHashValue hash_prefix(int length) const {
    return hash_substring(0, length);
  }

  PolyHashValue hash_substring(int left, int right) const {
    const int n = size();
    if (left < 0) {
      left = 0;
    }
    if (right > n) {
      right = n;
    }
    if (left >= right) {
      return PolyHashValue(0, 0);
    }
    return range_hash(prefix1_, prefix2_, left, right);
  }



  std::vector<PolyHashValue> all_hashes_of_length(int length) const {
    const int n = size();
    if (length < 0 || length > n) {
      return {};
    }
    std::vector<PolyHashValue> hashes;
    hashes.reserve(n - length + 1);
    for (int i = 0; i + length <= n; ++i) {
      hashes.push_back(hash_substring(i, i + length));
    }
    return hashes;
  }

  int compare_substrings(int left1, int right1, int left2, int right2) const {
    normalize_range(left1, right1);
    normalize_range(left2, right2);
    const int length1 = right1 - left1;
    const int length2 = right2 - left2;
    const int common = common_prefix(left1, left2, std::min(length1, length2));
    if (common == std::min(length1, length2)) {
      return (length1 > length2) - (length1 < length2);
    }
    return (values_[left1 + common] > values_[left2 + common]) -
           (values_[left1 + common] < values_[left2 + common]);
  }

  bool is_periodic(int left, int right, int period) const {
    normalize_range(left, right);
    const int length = right - left;
    if (period <= 0 || period > length || length % period != 0) return false;
    return period == length ||
           hash_substring(left, right - period) ==
               hash_substring(left + period, right);
  }

  int minimal_period(int left, int right) const {
    normalize_range(left, right);
    const int length = right - left;
    if (length <= 1) return length;
    std::vector<int> candidates;
    for (int divisor = 1; 1LL * divisor * divisor <= length; ++divisor) {
      if (length % divisor != 0) continue;
      candidates.push_back(divisor);
      if (divisor * divisor != length) candidates.push_back(length / divisor);
    }
    std::sort(candidates.begin(), candidates.end());
    for (int period : candidates) {
      if (is_periodic(left, right, period)) return period;
    }
    return length;
  }


  bool equal_substrings(int left1, int right1, int left2, int right2) const {
    if (right1 - left1 != right2 - left2) {
      return false;
    }
    return hash_substring(left1, right1) == hash_substring(left2, right2);
  }



  PolyHashValue concat(const PolyHashValue& left,
                         const PolyHashValue& right, int right_length) const {
    if (right_length < 0 || right_length >= static_cast<int>(power1_.size())) {
      return PolyHashValue(0, 0);
    }

    const int merged1 =
        static_cast<int>((static_cast<long long>(left.first) * power1_[right_length] +
                          right.first) % POLY_HASH_MOD1);
    const int merged2 =
        static_cast<int>((static_cast<long long>(left.second) * power2_[right_length] +
                          right.second) % POLY_HASH_MOD2);
    return PolyHashValue(merged1, merged2);
  }




 private:
  int base_;
  int base_mod1_;
  int base_mod2_;
  std::vector<int> prefix1_;
  std::vector<int> prefix2_;
  std::vector<int> power1_;
  std::vector<int> power2_;
  std::vector<long long> values_;


  static int normalize_mod(long long value, int mod) {
    long long x = value % mod;
    if (x < 0) {
      x += mod;
    }
    return static_cast<int>(x);
  }

  void normalize_range(int& left, int& right) const {
    left = std::max(0, std::min(left, size()));
    right = std::max(left, std::min(right, size()));
  }

  int common_prefix(int left1, int left2, int limit) const {
    int low = 0;
    int high = limit;
    while (low < high) {
      const int middle = (low + high + 1) / 2;
      if (hash_substring(left1, left1 + middle) ==
          hash_substring(left2, left2 + middle)) {
        low = middle;
      } else {
        high = middle - 1;
      }
    }
    return low;
  }

  PolyHashValue range_hash(const std::vector<int>& prefix1,
                            const std::vector<int>& prefix2,
                            int left, int right) const {
    const int len = right - left;
    int value1 =
        prefix1[right] -
        static_cast<int>((static_cast<long long>(prefix1[left]) * power1_[len]) % POLY_HASH_MOD1);
    if (value1 < 0) {
      value1 += POLY_HASH_MOD1;
    }

    int value2 =
        prefix2[right] -
        static_cast<int>((static_cast<long long>(prefix2[left]) * power2_[len]) % POLY_HASH_MOD2);
    if (value2 < 0) {
      value2 += POLY_HASH_MOD2;
    }

    return PolyHashValue(value1, value2);
  }

  int choose_base(int base) {
    int mod1 = normalize_mod(base, POLY_HASH_MOD1);
    int mod2 = normalize_mod(base, POLY_HASH_MOD2);
    if (mod1 <= 1 || mod2 <= 1) {
      base = POLY_HASH_BASE;
      mod1 = normalize_mod(base, POLY_HASH_MOD1);
      mod2 = normalize_mod(base, POLY_HASH_MOD2);
    }
    base_mod1_ = mod1;
    base_mod2_ = mod2;
    return base;
  }

  void push_prefix_value(long long raw_value, std::vector<int>& prefix1,
                         std::vector<int>& prefix2) const {
    const int value1 = normalize_mod(raw_value + 1, POLY_HASH_MOD1);
    const int value2 = normalize_mod(raw_value + 1, POLY_HASH_MOD2);
    prefix1.push_back(
        static_cast<int>((static_cast<long long>(prefix1.back()) * base_mod1_ + value1) % POLY_HASH_MOD1));
    prefix2.push_back(
        static_cast<int>((static_cast<long long>(prefix2.back()) * base_mod2_ + value2) % POLY_HASH_MOD2));
  }

  template <typename Container>
  void build_values(const Container& values, int base) {
    base_ = choose_base(base);
    const int n = static_cast<int>(values.size());

    prefix1_.assign(1, 0);
    prefix2_.assign(1, 0);
    power1_.assign(n + 1, 1);
    power2_.assign(n + 1, 1);
    values_.clear();
    values_.reserve(n);


    for (int i = 0; i < n; ++i) {
      power1_[i + 1] = static_cast<int>((static_cast<long long>(power1_[i]) * base_mod1_) % POLY_HASH_MOD1);
      power2_[i + 1] = static_cast<int>((static_cast<long long>(power2_[i]) * base_mod2_) % POLY_HASH_MOD2);
      values_.push_back(static_cast<long long>(values[i]));
      push_prefix_value(static_cast<long long>(values[i]), prefix1_, prefix2_);
    }


    EDULCNI_VIS(edulcni::live::array("poly_hash.prefix_first", prefix1_));
    EDULCNI_VIS(edulcni::live::array("poly_hash.prefix_second", prefix2_));
    EDULCNI_VIS(edulcni::live::array("poly_hash.power_first", power1_));
    EDULCNI_STEP("Polynomial hash prefix tables built");
  }
};


inline PolyHashValue poly_hash_string(const std::string& text,
                                      int base = POLY_HASH_BASE) {
  PolyHash hash(text, base);
  return hash.hash_prefix(static_cast<int>(text.size()));
}



inline bool poly_hash_equal_substrings(const PolyHash& lhs,
                                       int left1, int right1,
                                       const PolyHash& rhs,
                                       int left2, int right2) {
  if (lhs.base() != rhs.base() || right1 - left1 != right2 - left2) {
    return false;
  }
  return lhs.hash_substring(left1, right1) == rhs.hash_substring(left2, right2);
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  EDULCNI_VIS(edulcni::live::text("example.scenario", "Compare substrings and compose polynomial hashes."));
  EDULCNI_STEP("Example scenario initialized");
  EDULCNI_VIS(edulcni::internal::State::instance().delete_widget("example.scenario"));

  const std::string text = "abracadabra";
    PolyHash hash(text);
    assert(hash.size() == static_cast<int>(text.size()));
    assert(hash.hash_substring(0, 4) == poly_hash_string("abra"));
    assert(hash.equal_substrings(0, 4, 7, 11));
    const PolyHashValue left = hash.hash_substring(0, 4);
    const PolyHashValue right = hash.hash_substring(4, 7);
    assert(hash.concat(left, right, 3) == hash.hash_substring(0, 7));

  EDULCNI_VIS(edulcni::live::text("example.status", "All checks passed"));
  EDULCNI_STEP("Example scenario completed");

  cout << "ok\n";
  return 0;
}
