// Generated by tools/generate-solver-examples.mjs. Do not edit.
// Catalog entry: /solvers/convex_hull_trick

#include <bits/stdc++.h>
using namespace std;

#ifndef EDULCNI_VIS
#define EDULCNI_VIS(...) ((void)0)
#endif
#ifndef EDULCNI_STEP
#define EDULCNI_STEP(...) ((void)0)
#endif

class MonotoneConvexHullTrick {
 public:
  struct Line {
    long long slope;
    long long intercept;
    long long value(long long x) const { return slope * x + intercept; }
  };

  void add_line(long long slope, long long intercept) {
    Line line{slope, intercept};
    while (!lines_.empty() && lines_.back().slope == slope) {
      if (lines_.back().intercept <= intercept) return;
      lines_.pop_back();
    }
    while (lines_.size() >= 2 && redundant(lines_[lines_.size() - 2], lines_.back(), line))
      lines_.pop_back();
    lines_.push_back(line);
    EDULCNI_VIS(edulcni::live::lines("convex_hull_trick.lines", lines_));
    EDULCNI_STEP("Convex hull trick adds a line");
  }

  long long query(long long x) {
    while (lines_.size() >= 2 && lines_[0].value(x) >= lines_[1].value(x))
      lines_.pop_front();
    const long long result = lines_.front().value(x);
    EDULCNI_VIS(edulcni::live::lines("convex_hull_trick.lines", lines_));
    EDULCNI_VIS(edulcni::live::value("convex_hull_trick.query_x", x));
    EDULCNI_VIS(edulcni::live::value("convex_hull_trick.result", result));
    EDULCNI_STEP("Convex hull trick answers a query");
    return result;
  }

 private:
  std::deque<Line> lines_;

  static bool redundant(const Line& a, const Line& b, const Line& c) {
    return (__int128)(b.intercept - a.intercept) * (b.slope - c.slope) >=
           (__int128)(c.intercept - b.intercept) * (a.slope - b.slope);
  }
};

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  MonotoneConvexHullTrick hull;
    hull.add_line(5, 1);
    hull.add_line(3, 2);
    hull.add_line(1, 10);
    assert(hull.query(0) == 1);
    assert(hull.query(2) == 8);
    assert(hull.query(10) == 20);

  cout << "ok\n";
  return 0;
}
